___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/wJW61Y2/Used-cars.jpg width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Capstone Project of Data Analytics Module</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Car Price Prediction EDA</p>

## Introduction
Welcome to "***AutoScout Data Analysis Project***". This is the capstone project of ***Data Analysis*** Module. **Auto Scout** data which using for this project, scraped from the on-line car trading company in 2019, contains many features of 9 different car models. In this project, you will have the opportunity to apply many commonly used algorithms for Data Cleaning and Exploratory Data Analysis by using many Python libraries such as Numpy, Pandas, Matplotlib, Seaborn, Scipy you will analyze clean dataset.

### Some Reminders on Exploratory data analysis (EDA)

Exploratory data analysis (EDA) is an especially important activity in the routine of a data analyst or scientist. It enables an in depth understanding of the dataset, define or discard hypotheses and create predictive models on a solid basis. It uses data manipulation techniques and several statistical tools to describe and understand the relationship between variables and how these can impact business. By means of EDA, we can obtain meaningful insights that can impact analysis under the following questions (If a checklist is good enough for pilots to use every flight, it’s good enough for data scientists to use with every dataset).
1. What question are you trying to solve (or prove wrong)?
2. What kind of data do you have?
3. What’s missing from the data?
4. Where are the outliers?
5. How can you add, change or remove features to get more out of your data?

**``Exploratory data analysis (EDA)``** is often an **iterative brainstorming process** where you pose a question, review the data, and develop further questions to investigate before beginning model development work. The image below shows how the brainstorming phase is connected with that of understanding the variables and how this in turn is connected again with the brainstorming phase.<br>

<img src=https://i.ibb.co/k0MC950/EDA-Process.png width="300" height="100">

[Image Credit: Andrew D.](https://towardsdatascience.com/exploratory-data-analysis-in-python-a-step-by-step-process-d0dfa6bf94ee)

**``In this context, the project consists of 3 parts in general:``**
* **The first part** is related to 'Data Cleaning'. It deals with Incorrect Headers, Incorrect Format, Anomalies, and Dropping useless columns.
* **The second part** is related to 'Filling Data', in other words 'Imputation'. It deals with Missing Values. Categorical to numeric transformation is done as well.
* **The third part** is related to 'Handling Outliers of Data' via Visualization libraries. So, some insights will be extracted.

**``NOTE:``**  However, you are free to create your own style. You do NOT have to stick to the steps above. We, the DA & DV instructors, recommend you study each part separately to create a source notebook for each part title for your further studies.

# PART- 2 `( Handling With Missing Vales )`

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats.mstats import winsorize

import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

%matplotlib inline
# %matplotlib notebook

plt.rcParams["figure.figsize"] = (10,6)
# plt.rcParams['figure.dpi'] = 100

sns.set_style("whitegrid")
pd.set_option('display.float_format', lambda x: '%.3f' % x)

pd.options.display.max_rows = 1000
pd.options.display.max_columns = 150

In [ ]:
df= pd.read_csv("clean_scout.csv")

In [ ]:
df.shape

(15919, 28)

In [ ]:
df.head(3).T

,0,1,2
make_model,Audi A1,Audi A1,Audi A1
body_type,Sedans,Sedans,Sedans
price,15770,14500,14640
vat,VAT deductible,Price negotiable,VAT deductible
km,56013.000,80000.000,83450.000
Type,Used,Used,Used
Cylinders,3.000,4.000,NaN
Fuel,Diesel,Benzine,Diesel
Gears,NaN,7.000,NaN
Extras,"Alloy wheels,Catalytic Converter,Voice Control","Alloy wheels,Sport seats,Sport suspension,Voic...","Alloy wheels,Voice Control"
Previous_Owners,2.000,NaN,1.000
hp_kW,66.000,141.000,85.000
Inspection_new,Yes,NaN,NaN
age,3.000,2.000,3.000
Paint_Type,Metallic,NaN,Metallic
Upholstery_type,Cloth,Cloth,Cloth
Nr_of_Doors,5.000,3.000,4.000
Nr_of_Seats,5.000,4.000,4.000
Gearing_Type,Automatic,Automatic,Automatic
Displacement_cc,1422.000,1798.000,1598.000
Weight_kg,1220.000,1255.000,NaN
Drive_chain,front,front,front
Consumption_comb,3.800,5.600,3.800
CO2_Emission,99.000,129.000,99.000
Emission_Class,Euro 6,Euro 6,Euro 6
Comfort_Convenience,"Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Hil...","Air conditioning,Cruise control,Electrical sid..."
Entertainment_Media,"Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Hands-free equipment,On-board comput...","MP3,On-board computer"
Safety_Security,"ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Central door lock with r...","ABS,Central door lock,Daytime running lights,D..."

In [ ]:
df.isnull().sum()

make_model                 0
body_type                 60
price                      0
vat                     4513
km                      1024
Type                       2
Cylinders               5680
Fuel                       0
Gears                   4712
Extras                  2962
Previous_Owners         6640
hp_kW                     88
Inspection_new         11987
age                     1597
Paint_Type              5772
Upholstery_type         4871
Nr_of_Doors              212
Nr_of_Seats              977
Gearing_Type               0
Displacement_cc          496
Weight_kg               6974
Drive_chain             6858
Consumption_comb        2033
CO2_Emission            2436
Emission_Class          3628
Comfort_Convenience      920
Entertainment_Media     1374
Safety_Security          982
dtype: int64

In [ ]:
def describe(column):
    print("Column Name    : ", column)
    print("-"*40)
    print("Per_of_nulls   : ", "%", round(df[column].isnull().sum()/df.shape[0]*100, 2))
    print("Num_of_nulls   : ", df[column].isnull().sum())
    print("Num_of_uniques : ", df[column].nunique())
    print("-"*40)
    print(df[column].value_counts(dropna = False))

### Let's examine and fill the missing values of all the columns/features one by one

### body_type

In [ ]:
describe("body_type")

Column Name    :  body_type
----------------------------------------
Per_of_nulls   :  % 0.38
Num_of_nulls   :  60
Num_of_uniques :  9
----------------------------------------
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [ ]:
df.body_type.unique()

array(['Sedans', 'Station wagon', 'Compact', 'Other', 'Coupe', 'Van',
       'Off-Road', 'Convertible', nan, 'Transporter'], dtype=object)

In [ ]:
df.body_type.value_counts(dropna=False)

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [ ]:
df.body_type.replace("Other", np.nan, inplace=True)

In [ ]:
df.body_type.value_counts(dropna=False)

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
NaN               350
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [ ]:
df.groupby("make_model")["body_type"].value_counts(dropna=False)

make_model      body_type
Audi A1         Sedans           1538
                Compact          1039
                Station wagon      21
                NaN                13
                Coupe               2
                Van                 1
Audi A2         Off-Road            1
Audi A3         Sedans           2598
                Station wagon     282
                Compact           182
                NaN                23
                Convertible         8
                Coupe               4
Opel Astra      Station wagon    1211
                Sedans           1053
                Compact           185
                NaN                74
                Coupe               2
                Off-Road            1
Opel Corsa      Compact          1230
                Sedans            875
                NaN                89
                Coupe              13
                Transporter         7
                Off-Road            3
                Van                 2
Opel Insignia   Station wagon    1611
                Sedans            900
                NaN                51
                Compact            27
                Off-Road            7
                Coupe               1
                Van                 1
Renault Clio    Sedans            918
                Compact           484
                Station wagon     337
                NaN                66
                Transporter        29
                Off-Road            2
                Van                 2
                Coupe               1
Renault Duster  Off-Road           34
Renault Espace  Van               777
                Station wagon      91
                Transporter        52
                NaN                34
                Sedans             21
                Off-Road            8
                Compact             6
                Coupe               2
Name: body_type, dtype: int64

In [ ]:
for group in list(df["make_model"].unique()):
    cond = df["make_model"]==group
    mode = list(df[cond]["body_type"].mode())
    if mode != []:
        df.loc[cond, "body_type"] = df.loc[cond, "body_type"].fillna(df[cond]["body_type"].mode()[0])
    else:
        df.loc[cond, "body_type"] = df.loc[cond, "body_type"].fillna(df["body_type"].mode()[0])

In [ ]:
df.groupby("make_model")["body_type"].value_counts(dropna=False)

make_model      body_type
Audi A1         Sedans           1551
                Compact          1039
                Station wagon      21
                Coupe               2
                Van                 1
Audi A2         Off-Road            1
Audi A3         Sedans           2621
                Station wagon     282
                Compact           182
                Convertible         8
                Coupe               4
Opel Astra      Station wagon    1285
                Sedans           1053
                Compact           185
                Coupe               2
                Off-Road            1
Opel Corsa      Compact          1319
                Sedans            875
                Coupe              13
                Transporter         7
                Off-Road            3
                Van                 2
Opel Insignia   Station wagon    1662
                Sedans            900
                Compact            27
                Off-Road            7
                Coupe               1
                Van                 1
Renault Clio    Sedans            984
                Compact           484
                Station wagon     337
                Transporter        29
                Off-Road            2
                Van                 2
                Coupe               1
Renault Duster  Off-Road           34
Renault Espace  Van               811
                Station wagon      91
                Transporter        52
                Sedans             21
                Off-Road            8
                Compact             6
                Coupe               2
Name: body_type, dtype: int64

In [ ]:
def grouping_fill(df, group_col, col_name):
    for group in list(df[group_col].unique()):
        cond = df[group_col]==group
        mode = list(df[cond][col_name].mode())
        if mode != []:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[cond][col_name].mode()[0])
        else:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[col_name].mode()[0])
    print("Number of NaN : ",df[col_name].isnull().sum())
    print("------------------")
    print(df.groupby([group_col])[col_name].value_counts(dropna=False))

### vat

In [ ]:
describe("vat")

Column Name    :  vat
----------------------------------------
Per_of_nulls   :  % 28.35
Num_of_nulls   :  4513
Num_of_uniques :  2
----------------------------------------
VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64

It has been determined that the vat column is related to other columns.

In [ ]:
df.vat.fillna(method="ffill", inplace=True)

In [ ]:
df.vat.value_counts(dropna=False)

VAT deductible      15048
Price negotiable      871
Name: vat, dtype: int64

### age

In [ ]:
describe("age")

Column Name    :  age
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  0
Num_of_uniques :  4
----------------------------------------
1.000    4533
0.000    4430
3.000    3679
2.000    3277
Name: age, dtype: int64

In [ ]:
df.age.fillna("-", inplace=True)

In [ ]:
df.groupby("age").km.describe()

,count,mean,std,min,25%,50%,75%,max
age,,,,,,,,
0.000,3445.000,1642.959,4830.832,0.000,10.000,14.000,1380.000,127022.000
1.000,4495.000,18020.276,11049.489,1.000,9983.500,17869.000,25068.000,136000.000
2.000,3276.000,41748.577,28279.313,1.000,21572.500,34752.000,54755.000,317000.000
3.000,3679.000,77450.063,39145.119,10.000,48000.000,72945.000,99950.000,291800.000

In [ ]:
df[df["age"]=="-"]["km"].value_counts(dropna=False)

Series([], Name: km, dtype: int64)

When groupby operation is performed according to age and km, 75% values of age descriptions are taken to assign unknown values according to age ranges.

In [ ]:
age0 =(df["km"]<=3000)
age1 =((df["km"]>3000) & (df["km"]<=25080))
age2 =((df["km"]>25080) & (df["km"]<=54806))
age3 =(df["km"]>54806)

In [ ]:
df.loc[age0,'age'] = df.loc[age0,'age'].replace('-', 0)
df.loc[age1,'age'] = df.loc[age1,'age'].replace('-', 1)
df.loc[age2,'age'] = df.loc[age2,'age'].replace('-', 2)
df.loc[age3,'age'] = df.loc[age3,'age'].replace('-', 3)

In [ ]:
df.age.value_counts(dropna=False)

1.000    4533
0.000    4430
3.000    3679
2.000    3277
Name: age, dtype: int64

In [ ]:
df.groupby(["make_model","age"]).price.mean()

make_model      age
Audi A1         0.000   23871.578
                1.000   18448.255
                2.000   16625.734
                3.000   14489.769
Audi A2         1.000   28200.000
Audi A3         0.000   24924.341
                1.000   22504.332
                2.000   19939.557
                3.000   16466.090
Opel Astra      0.000   21295.017
                1.000   16134.623
                2.000   13008.951
                3.000   11357.733
Opel Corsa      0.000   13472.538
                1.000   11304.836
                2.000    9249.490
                3.000    8195.207
Opel Insignia   0.000   32104.554
                1.000   21390.168
                2.000   16995.141
                3.000   13606.710
Renault Clio    0.000   11890.551
                1.000   14699.366
                2.000   10814.541
                3.000    9349.533
Renault Duster  0.000   13230.176
Renault Espace  0.000   39779.750
                1.000   32022.743
                2.000   26371.694
                3.000   21878.583
Name: price, dtype: float64

When the prices are examined according to Make Model and Age, it is observed that the prices of missing values are similar to the prices of 0 years old.

In [ ]:
df.age.replace("-",0, inplace=True)

In [ ]:
df.age.value_counts(dropna=False)

1.000    4533
0.000    4430
3.000    3679
2.000    3277
Name: age, dtype: int64

### km

In [ ]:
describe("km")

Column Name    :  km
----------------------------------------
Per_of_nulls   :  % 6.43
Num_of_nulls   :  1024
Num_of_uniques :  6689
----------------------------------------
10.000       1045
NaN          1024
1.000         367
5.000         170
50.000        148
             ...
67469.000       1
43197.000       1
10027.000       1
35882.000       1
57.000          1
Name: km, Length: 6690, dtype: int64

In [ ]:
df.groupby("age")["km"].mean()

age
0.000    1642.959
1.000   18020.276
2.000   41748.577
3.000   77450.063
Name: km, dtype: float64

In [ ]:
df.groupby(["make_model","age"])["km"].mean()

make_model      age
Audi A1         0.000    2099.239
                1.000   13793.652
                2.000   25821.713
                3.000   54332.286
Audi A2         1.000   26166.000
Audi A3         0.000    1517.817
                1.000   18410.524
                2.000   43853.141
                3.000   90092.983
Opel Astra      0.000    2351.275
                1.000   21442.709
                2.000   49981.779
                3.000   89086.697
Opel Corsa      0.000     913.544
                1.000   17431.599
                2.000   39942.383
                3.000   62947.974
Opel Insignia   0.000    2411.429
                1.000   22158.271
                2.000   47732.104
                3.000   93182.342
Renault Clio    0.000     572.900
                1.000   15375.462
                2.000   36660.153
                3.000   68615.436
Renault Duster  0.000     101.000
Renault Espace  0.000    1469.460
                1.000   14144.860
                2.000   41886.635
                3.000   74400.567
Name: km, dtype: float64

In [ ]:
df.groupby(["make_model","body_type","age"])["km"].mean()

make_model      body_type      age
Audi A1         Compact        0.000     2584.929
                               1.000    14545.929
                               2.000    23698.348
                               3.000    55367.338
                Coupe          2.000    50000.000
                               3.000    27300.000
                Sedans         0.000     1829.297
                               1.000    13344.021
                               2.000    27073.367
                               3.000    53850.165
                Station wagon  0.000     3100.000
                               1.000    14513.455
                               2.000    20319.000
                               3.000    48807.400
                Van            0.000     3000.000
Audi A2         Off-Road       1.000    26166.000
Audi A3         Compact        0.000     9586.471
                               1.000    16461.586
                               2.000    44023.385
                               3.000    96799.516
                Convertible    1.000    12388.000
                               2.000    22524.750
                               3.000    37000.000
                Coupe          2.000    24990.000
                               3.000    27505.333
                Sedans         0.000     1218.547
                               1.000    18570.180
                               2.000    44313.873
                               3.000    89473.784
                Station wagon  0.000     2067.174
                               1.000    17189.031
                               2.000    41630.750
                               3.000    90422.896
Opel Astra      Compact        0.000     1612.980
                               1.000    12785.818
                               2.000    37580.418
                               3.000    83062.000
                Coupe          0.000          NaN
                               3.000    20940.000
                Off-Road       1.000    12607.000
                Sedans         0.000     2037.130
                               1.000    19663.959
                               2.000    38161.807
                               3.000    75665.513
                Station wagon  0.000     2835.188
                               1.000    23796.150
                               2.000    62791.841
                               3.000    95739.829
Opel Corsa      Compact        0.000      901.846
                               1.000    16316.094
                               2.000    37185.590
                               3.000    57373.318
                Coupe          0.000        4.000
                               2.000    36330.000
                               3.000    49815.200
                Off-Road       2.000    50729.000
                Sedans         0.000      972.535
                               1.000    19031.416
                               2.000    42049.688
                               3.000    69142.187
                Transporter    0.000       35.000
                               2.000    97000.000
                               3.000    88471.000
                Van            3.000    33633.000
Opel Insignia   Compact        0.000     3445.625
                               1.000     7750.500
                               2.000    51149.250
                               3.000    74102.750
                Coupe          2.000    28142.000
                Off-Road       0.000       50.500
                               3.000   159000.000
                Sedans         0.000     2936.807
                               1.000    18919.730
                               2.000    48115.518
                               3.000    74128.563
                Station wagon  0.000     2116.940
                               1.000    24062.916
                               2.000    47472.472
                               3.000    98700.137
                Van            1.000    23726.000
Renault Clio    Compact        0.000      176.571
                               1.000    11791.863
                               2.000    31541.500
                               3.000    66639.517
                Coupe          2.000    24500.000
                Off-Road       0.000      500.000
                               3.000    95000.000
                Sedans         0.000      287.723
                               1.000    13428.273
                               2.000    38288.017
                               3.000    68210.267
                Station wagon  0.000     3789.062
                               1.000    27379.546
                               2.000    37549.000
                               3.000    70108.041
                Transporter    0.000       39.667
                               1.000     5440.500
                               2.000    33628.333
                               3.000    76675.364
                Van            1.000    22613.000
                               2.000    36000.000
Renault Duster  Off-Road       0.000      101.000
Renault Espace  Compact        0.000      533.333
                               2.000    36682.000
                               3.000    52353.500
                Coupe          0.000       10.000
                               1.000    14478.000
                Off-Road       1.000    32400.000
                               2.000    36607.200
                               3.000   141522.000
                Sedans         0.000     3000.000
                               1.000    19127.182
                               2.000    51946.667
                               3.000    48189.000
                Station wagon  0.000     3699.000
                               1.000    11998.000
                               2.000    46066.923
                               3.000    72785.135
                Transporter    0.000       10.000
                               1.000    10842.000
                               2.000    53188.889
                               3.000    71981.703
                Van            0.000     1397.977
                               1.000    13921.698
                               2.000    40774.101
                               3.000    75385.500
Name: km, dtype: float64

In [ ]:
df.km.fillna(df.groupby(["body_type","age"]).km.transform("mean"),inplace=True)

In [ ]:
describe("km")

Column Name    :  km
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  0
Num_of_uniques :  6700
----------------------------------------
10.000        1045
1520.636       452
1.000          367
1382.493       253
2493.427       229
              ...
157391.000       1
180573.000       1
38994.000        1
144063.000       1
57.000           1
Name: km, Length: 6700, dtype: int64

In [ ]:
df.km.value_counts(dropna=False)

10.000        1045
1520.636       452
1.000          367
1382.493       253
2493.427       229
              ...
157391.000       1
180573.000       1
38994.000        1
144063.000       1
57.000           1
Name: km, Length: 6700, dtype: int64

### Type

In [ ]:
describe("Type")

Column Name    :  Type
----------------------------------------
Per_of_nulls   :  % 0.01
Num_of_nulls   :  2
Num_of_uniques :  5
----------------------------------------
Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: Type, dtype: int64

In [ ]:
df.Type.fillna("-", inplace=True)

In [ ]:
df.groupby(["Type","make_model","age"]).km.mean()

Type            make_model      age
-               Audi A3         0.000     1520.636
                                3.000   115137.000
Demonstration   Audi A1         0.000     3784.227
                                1.000     9931.158
                                2.000    22963.500
                Audi A3         0.000     4971.878
                                1.000    12801.188
                                2.000    27950.000
                Opel Astra      0.000     2885.858
                                1.000     7319.938
                                2.000    68500.000
                Opel Corsa      0.000     1230.099
                                1.000     2915.500
                Opel Insignia   0.000     3972.656
                                1.000    13721.000
                                2.000    27175.000
                                3.000    56000.000
                Renault Clio    0.000      655.505
                                1.000     5555.848
                                2.000    10014.000
                                3.000    35000.000
                Renault Espace  0.000     4402.758
                                1.000     9918.517
                                2.000    24883.000
Employee's car  Audi A1         0.000     4504.301
                                1.000    12141.076
                                2.000    17377.750
                                3.000    48103.800
                Audi A2         1.000    26166.000
                Audi A3         0.000     3869.452
                                1.000    18197.567
                                2.000    31584.750
                                3.000    56954.625
                Opel Astra      0.000     5451.056
                                1.000    23088.033
                                2.000    52783.000
                                3.000    95000.000
                Opel Corsa      0.000     3131.397
                                1.000    16942.113
                                2.000    42133.550
                                3.000   103000.000
                Opel Insignia   0.000     7402.606
                                1.000    23911.075
                                2.000    48409.000
                Renault Clio    0.000      885.568
                                1.000    24363.463
                                2.000    46621.083
                                3.000    60892.000
                Renault Espace  0.000     2327.581
                                1.000    15418.926
                                2.000    22298.167
                                3.000    50054.000
New             Audi A1         0.000      991.168
                Audi A3         0.000      664.948
                                1.000        7.000
                Opel Astra      0.000     1009.605
                Opel Corsa      0.000      505.457
                Opel Insignia   0.000     1187.360
                Renault Clio    0.000      675.862
                                1.000      100.000
                Renault Duster  0.000      116.684
                Renault Espace  0.000      547.690
                                1.000    14012.363
Pre-registered  Audi A1         0.000      172.910
                                1.000     3426.130
                                2.000       10.000
                Audi A3         0.000      401.788
                                1.000     1421.765
                Opel Astra      0.000      145.786
                                1.000      816.667
                                2.000     4000.000
                Opel Corsa      0.000       65.380
                                1.000       47.276
                                2.000       99.000
                Opel Insignia   0.000      346.843
                                1.000     7939.984
                                2.000        1.000
                Renault Clio    0.000      311.171
                                1.000     2301.477
                                2.000     6210.500
                                3.000       10.000
                Renault Espace  0.000       52.191
                                1.000     6987.492
                                2.000       77.000
Used            Audi A1         0.000     2836.604
                                1.000    14617.212
                                2.000    26086.731
                                3.000    54382.194
                Audi A3         0.000     4389.342
                                1.000    19142.736
                                2.000    44593.116
                                3.000    90389.723
                Opel Astra      0.000     5041.101
                                1.000    21527.391
                                2.000    49971.044
                                3.000    89075.325
                Opel Corsa      0.000     3258.851
                                1.000    18883.428
                                2.000    39931.479
                                3.000    62854.613
                Opel Insignia   0.000     5103.203
                                1.000    21934.692
                                2.000    48031.056
                                3.000    93247.919
                Renault Clio    0.000     2049.780
                                1.000    16321.291
                                2.000    36719.399
                                3.000    68883.593
                Renault Duster  0.000      101.000
                Renault Espace  0.000     2026.692
                                1.000    16272.654
                                2.000    44076.110
                                3.000    74481.993
Name: km, dtype: float64

In [ ]:
audiA3_0= (df["make_model"]=="Audi A3") & (df["age"]==0)
audiA3_3= (df["make_model"]=="Audi A3") & (df["age"]==3)

In [ ]:
df.groupby(["Type", audiA3_0]).km.describe()

                         count       mean       std        min        25%  \
Type
-              False     1.000 115137.000       NaN 115137.000 115137.000
               True      1.000   1520.636       NaN   1520.636   1520.636
Demonstration  False   755.000   4959.665  7445.566      3.000    518.000
               True     41.000   4971.878  3092.353     50.000   3000.000
Employee's car False   980.000  20395.325 14696.980      1.000   9900.000
               True     31.000   3869.452  5402.688     10.000    100.000
New            False  1325.000    935.513   970.880      0.000     10.000
               True    325.000    664.948   933.589      0.000     10.000
Pre-registered False  1081.000    594.819  2650.123      1.000     10.000
               True    283.000    401.788  1070.257      1.000     10.000
Used           False 10950.000  44166.607 38288.826      1.000  16300.000
               True    146.000   4389.342 12986.968      1.000     27.000

                            50%        75%        max
Type
-              False 115137.000 115137.000 115137.000
               True    1520.636   1520.636   1520.636
Demonstration  False   2998.000   5555.000  78000.000
               True    5000.000   6000.000  14000.000
Employee's car False  20500.000  27188.000 112789.000
               True     500.000   5900.000  18000.000
New            False   1382.493   1520.636  14012.363
               True      10.000   1520.636   2493.427
Pre-registered False     10.000     50.000  23794.952
               True      10.000     80.000   8000.000
Used           False  30000.000  64000.000 317000.000
               True     101.000   5000.000 127022.000

In [ ]:
df.loc[audiA3_0,'Type']= df.loc[audiA3_0,'Type'].replace('-', "New")

In [ ]:
df.groupby(["Type", audiA3_3]).km.describe()

                         count       mean       std        min        25%  \
Type
-              True      1.000 115137.000       NaN 115137.000 115137.000
Demonstration  False   796.000   4960.294  7284.135      3.000    732.500
Employee's car False  1003.000  19592.955 14284.056      1.000   9023.500
               True      8.000  56954.625 26796.572   7790.000  40700.000
New            False  1651.000    882.606   969.199      0.000     10.000
Pre-registered False  1364.000    554.769  2409.990      1.000     10.000
Used           False 10287.000  39966.939 35992.826      1.000  14931.233
               True    809.000  90389.723 36420.969     35.000  63000.000

                            50%        75%        max
Type
-              True  115137.000 115137.000 115137.000
Demonstration  False   3000.000   5922.500  78000.000
Employee's car False  19950.000  27046.000 112789.000
               True   58481.000  81095.750  85100.000
New            False   1382.493   1520.636  14012.363
Pre-registered False     10.000     50.000  23794.952
Used           False  27950.000  56000.000 317000.000
               True   88067.000 113000.000 291800.000

In [ ]:
df.loc[audiA3_3,'Type']= df.loc[audiA3_3,'Type'].replace('-', "Used")

In [ ]:
df.Type.value_counts(dropna=False)

Used              11097
New                1651
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: Type, dtype: int64

### Cylinders

In [ ]:
describe("Cylinders")

Column Name    :  Cylinders
----------------------------------------
Per_of_nulls   :  % 35.68
Num_of_nulls   :  5680
Num_of_uniques :  7
----------------------------------------
4.000    8105
NaN      5680
3.000    2104
5.000      22
6.000       3
8.000       2
2.000       2
1.000       1
Name: Cylinders, dtype: int64

In [ ]:
df.groupby("Cylinders").hp_kW.mean()

Cylinders
1.000    66.000
2.000   123.500
3.000    73.835
4.000    91.600
5.000   271.409
6.000   100.000
8.000    93.500
Name: hp_kW, dtype: float64

In [ ]:
df.drop("Cylinders", axis=1, inplace=True)

### Gears

In [ ]:
describe("Gears")

In [ ]:
df.Gears.fillna("-",inplace=True)

In [ ]:
df.groupby(["body_type","make_model","Gearing_Type","Gears"]).price.describe()

                                                    count      mean       std  \
body_type     make_model     Gearing_Type   Gears
Compact       Audi A1        Automatic      5.0     3.000 22184.333  3421.302
                                            6.0     6.000 21038.333  4282.039
                                            7.0   199.000 22059.251  3918.116
                                            8.0     1.000 16880.000       NaN
                                            -     253.000 21640.427  4965.500
                             Manual         5.0   277.000 16329.469  3040.933
                                            6.0    77.000 20538.299  2061.004
                                            -     220.000 16756.727  3182.991
                             Semi-automatic 7.0     3.000 24028.333  7208.440
              Audi A3        Automatic      6.0     4.000 17820.000  1839.438
                                            7.0    56.000 19340.982  3092.938
                                            -      10.000 19448.400  2145.488
                             Manual         5.0     1.000 18900.000       NaN
                                            6.0    87.000 16091.356  3171.229
                                            7.0     1.000 15000.000       NaN
                                            -       9.000 17373.333  3100.387
                             Semi-automatic 6.0     1.000 24950.000       NaN
                                            7.0    13.000 38341.308  9924.338
              Opel Astra     Automatic      5.0     6.000 17182.333  1442.086
                                            6.0    25.000 25286.080  9242.129
                                            -      12.000 21568.750  7846.095
                             Manual         5.0    24.000 15659.458  2318.536
                                            6.0   110.000 13690.618  2415.385
                                            -       3.000 10030.000   760.723
                             Semi-automatic 5.0     3.000 17866.667  2027.519
                                            -       2.000 18700.000   353.553
              Opel Corsa     Automatic      5.0    80.000 13337.712  1995.726
                                            6.0   266.000 14690.575  1778.283
                                            8.0     1.000 14770.000       NaN
                                            -     282.000 14214.404  1794.742
                             Manual         5.0   446.000  9253.117  1393.818
                                            6.0    27.000  7900.037  2505.112
                                            -     197.000  9001.234  1262.150
                             Semi-automatic 1.0     1.000 11000.000       NaN
                                            5.0    10.000 13179.900  2344.363
                                            -       9.000 13486.778  1246.997
              Opel Insignia  Automatic      6.0     8.000 34854.125  6916.641
                                            8.0     1.000 25900.000       NaN
                                            -       1.000 13490.000       NaN
                             Manual         6.0    17.000 26688.765 12163.560
              Renault Clio   Automatic      1.0     1.000 23990.000       NaN
                                            5.0     2.000 15722.500  1735.947
                                            6.0    66.000 16548.167  4376.020
                                            7.0     2.000 28255.000  2100.107
                                            -     132.000 15901.023  2807.837
                             Manual         5.0   160.000  9537.606  1328.611
                                            6.0     2.000 10332.000   922.067
                                            -     118.000 10549.008  1250.182
                             Semi-automatic 6.0     1.000 27900.000       NaN
              Renault Espace Automatic      6.0     2.000 38250.000  6717.514
                                            7.0     1.000 17900.000       NaN
                                            -       3.000 28626.667  9896.264
Convertible   Audi A3        Automatic      7.0     3.000 17931.000  6119.852
                             Semi-automatic 6.0     2.000 25450.000  7707.464
                                            7.0     3.000 39516.667 14464.814
Coupe         Audi A1        Manual         5.0     1.000 13950.000       NaN
                                            -       1.000 15900.000       NaN
              Audi A3        Automatic      7.0     4.000 17745.000   962.653
              Opel Astra     Automatic      6.0     1.000 14490.000       NaN
                                            -       1.000 29990.000       NaN
              Opel Corsa     Automatic      5.0     1.000  6900.000       NaN
                                            -       1.000 10990.000       NaN
                             Manual         5.0     8.000  8793.750  1509.124
                                            6.0     1.000  7800.000       NaN
                                            -       1.000  7500.000       NaN
                             Semi-automatic 5.0     1.000 10500.000       NaN
              Opel Insignia  Manual         -       1.000 17094.000       NaN
              Renault Clio   Automatic      6.0     1.000 17990.000       NaN
              Renault Espace Automatic      -       2.000 30567.000  5052.985
Off-Road      Audi A2        Manual         -       1.000 28200.000       NaN
              Opel Astra     Automatic      6.0     1.000 18590.000       NaN
              Opel Corsa     Manual         5.0     2.000  7900.000     0.000
                                            6.0     1.000  8700.000       NaN
              Opel Insignia  Automatic      6.0     1.000 32345.000       NaN
                                            8.0     2.000 33140.500  2312.946
                                            -       1.000 12750.000       NaN
                             Manual         6.0     3.000 31594.333  2702.337
              Renault Clio   Automatic      6.0     1.000 17990.000       NaN
                             Manual         5.0     1.000  7700.000       NaN
              Renault Duster Automatic      -       8.000 14641.500  1487.576
                             Manual         6.0    25.000 12873.760  1393.386
                                            -       1.000 10850.000       NaN
              Renault Espace Automatic      5.0     2.000 27850.000     0.000
                                            6.0     3.000 28300.000  5302.829
                                            -       2.000 19900.000  7071.068
                             Manual         6.0     1.000 25700.000       NaN
Sedans        Audi A1        Automatic      5.0    14.000 18078.571  1329.649
                                            6.0    11.000 22974.364  5983.728
                                            7.0   398.000 21320.038  4146.217
                                            8.0     1.000 20500.000       NaN
                                            -     257.000 21100.016  4361.498
                             Manual         5.0   513.000 15490.267  2529.015
                                            6.0    89.000 21144.978  2273.883
                                            7.0     1.000 15500.000       NaN
                                            -     213.000 16629.319  2916.426
                             Semi-automatic 6.0     1.000 37900.000       NaN
                                            7.0    52.000 20432.635  5370.504
                                            -       1.000 20900.000       NaN
              Audi A3        Automatic      6.0    72.000 18276.889  2859.820
                                            7.0   790.000 21967.932  3273.470
                                            -     312.000 21566.500  3834.391
                             Manual         5.0     1.000 12949.000       NaN
                                            6.0   935.000 19965.568  3279.827
                                            7.0     7.000 21841.429  2286.084
                                            -     264.000 18429.761  3344.274
                             Semi-automatic 6.0    46.000 25793.239  5776.733
                                            7.0   193.000 26548.461 10645.292
                                            -       1.000 28300.000       NaN
              Opel Astra     Automatic      5.0    35.000 15350.229  2052.656
                                            6.0   218.000 20153.335  5201.872
                                            -     149.000 17986.040  4061.570
                             Manual         5.0   222.000 15279.586  2403.053
                                            6.0   236.000 13714.538  3274.578
                                            -     185.000 13228.292  2273.591
                             Semi-automatic 5.0     3.000 14993.000  1799.035
                                            6.0     2.000 14685.000  1675.843
                                            -       3.000 16113.333  1430.047
              Opel Corsa     Automatic      5.0    40.000 11807.300  1698.677
                                            6.0   155.000 13887.284  2350.215
                                            -      44.000 13273.477  1770.621
                             Manual         2.0     1.000  9880.000       NaN
                                            5.0   527.000  8963.091  1407.477
                                            6.0     8.000  8428.625  1355.515
                                            -      71.000  8429.958  1125.842
                             Semi-automatic 5.0    21.000 11194.762  1838.893
                                            6.0     4.000  8750.000  1258.306
                                            -       4.000 12932.500  1882.841
              Opel Insignia  Automatic      5.0     4.000 11550.000   115.470
                                            6.0   233.000 22726.052  7682.973
                                            7.0     1.000 10400.000       NaN
                                            8.0    50.000 32151.000  6383.716
                                            -      77.000 22130.688  7058.729
                             Manual         6.0   424.000 19858.969  6798.594
                                            8.0     1.000 19480.000       NaN
                                            -     110.000 18491.427  3887.047
              Renault Clio   Automatic      5.0     6.000 11696.500  2260.271
                                            6.0   196.000 16932.745  4704.454
                                            -     103.000 16774.097  3636.900
                             Manual         5.0   542.000  9372.055  1313.354
                                            6.0     5.000  9571.000   227.936
                                            50.0    1.000 10798.000       NaN
                                            -      93.000  9351.559  1201.951
                             Semi-automatic 6.0    38.000 17161.816  5242.839
              Renault Espace Automatic      6.0     3.000 30016.667  1529.978
                                            7.0     3.000 30763.333  5609.459
                                            -      12.000 29906.417  7576.961
                             Manual         -       3.000 29961.333 14875.796
Station wagon Audi A1        Automatic      7.0     3.000 23193.000  5069.983
                                            -       5.000 20970.400  4904.192
                             Manual         5.0    10.000 15574.000  1198.621
                                            6.0     1.000 13979.000       NaN
                                            -       2.000 14944.500  1337.139
              Audi A3        Automatic      6.0     6.000 19143.333  3117.420
                                            7.0    40.000 21534.850  3693.930
                                            -      63.000 21875.270  3932.570
                             Manual         6.0   105.000 20175.524  3540.220
                                            -      67.000 19347.194  4204.700
                             Semi-automatic 7.0     1.000 63900.000       NaN
              Opel Astra     Automatic      5.0    10.000 15287.300  2763.519
                                            6.0   381.000 19322.570  5410.162
                                            7.0     1.000 14950.000       NaN
                                            -     253.000 17384.435  4664.104
                             Manual         5.0    80.000 15018.800  3248.191
                                            6.0   372.000 12965.766  3276.486
                                            -     183.000 11473.525  2586.201
                             Semi-automatic 5.0     2.000 14425.000  2156.676
                                            6.0     2.000 16430.000  1315.219
                                            -       1.000 14990.000       NaN
              Opel Insignia  Automatic      5.0     2.000 19900.000     0.000
                                            6.0   477.000 22261.296  7659.660
                                            7.0     1.000 12500.000       NaN
                                            8.0   165.000 29127.618  7280.278
                                            -     300.000 20110.553  6939.088
                             Manual         5.0     1.000 27980.000       NaN
                                            6.0   509.000 20536.403  7611.398
                                            8.0     2.000 32375.000  3358.757
                                            -     205.000 17330.927  4552.058
              Renault Clio   Automatic      5.0     1.000  9990.000       NaN
                                            6.0    71.000 14106.944  2826.220
                                            7.0     1.000 16995.000       NaN
                                            -      37.000 15557.459  1994.992
                             Manual         5.0   159.000  9633.811  1219.572
                                            6.0     4.000  9591.000  1591.663
                                            -      58.000  8838.069   913.834
                             Semi-automatic 6.0     6.000 10466.667  2542.964
              Renault Espace Automatic      6.0    54.000 25568.241  8854.389
                                            7.0    21.000 31323.333  6878.447
                                            -       9.000 30627.667  9335.683
                             Manual         6.0     5.000 20108.000  3233.005
                                            7.0     1.000 30980.000       NaN
                             Semi-automatic 6.0     1.000 39990.000       NaN
Transporter   Opel Corsa     Manual         5.0     7.000  7650.000  2271.930
              Renault Clio   Manual         5.0    11.000  8032.636  1482.515
                                            -      18.000  8769.778  1189.769
              Renault Espace Automatic      6.0    18.000 23550.000  4556.250
                                            7.0     3.000 23583.333  1414.508
                                            -       2.000 22750.000   353.553
                             Manual         6.0     7.000 19906.857  4153.227
                             Semi-automatic 6.0    22.000 22547.227  4257.310
Van           Audi A1        Automatic      6.0     1.000 29000.000       NaN
              Opel Corsa     Manual         -       2.000  7900.000     0.000
              Opel Insignia  Manual         6.0     1.000 20980.000       NaN
              Renault Clio   Manual         -       2.000  9650.000   353.553
              Renault Espace Automatic      3.0     2.000 50432.000  5334.414
                                            4.0     2.000 50950.000     0.000
                                            6.0   302.000 29978.202  7497.319
                                            7.0   104.000 36930.558  9228.273
                                            9.0     6.000 52208.500  2735.327
                                            -     314.000 30763.793  7892.898
                             Manual         6.0    50.000 22798.560  6056.783
                                            7.0     1.000 36590.000       NaN
                                            -      14.000 27123.214  8657.066
                             Semi-automatic 6.0    11.000 28885.455 11439.110
                                            7.0     1.000 19900.000       NaN
                                            -       4.000 26445.000  4549.289

                                                        min       25%  \
body_type     make_model     Gearing_Type   Gears
Compact       Audi A1        Automatic      5.0   18497.000 20648.500
                                            6.0   16430.000 18725.000
                                            7.0   13990.000 18970.000
                                            8.0   16880.000 16880.000
                                            -     13880.000 16975.000
                             Manual         5.0    9950.000 13990.000
                                            6.0   12550.000 19588.000
                                            -     10490.000 14430.000
                             Semi-automatic 7.0   17945.000 20047.500
              Audi A3        Automatic      6.0   15490.000 17297.500
                                            7.0   13950.000 16900.000
                                            -     16950.000 17895.500
                             Manual         5.0   18900.000 18900.000
                                            6.0   12900.000 13500.000
                                            7.0   15000.000 15000.000
                                            -     14530.000 15950.000
                             Semi-automatic 6.0   24950.000 24950.000
                                            7.0   24860.000 35495.000
              Opel Astra     Automatic      5.0   15945.000 15962.250
                                            6.0   12490.000 15400.000
                                            -     12999.000 14491.250
                             Manual         5.0   10791.000 13899.000
                                            6.0    8450.000 11955.000
                                            -      9490.000  9595.000
                             Semi-automatic 5.0   15900.000 16825.000
                                            -     18450.000 18575.000
              Opel Corsa     Automatic      5.0    8450.000 12372.500
                                            6.0    9470.000 13746.000
                                            8.0   14770.000 14770.000
                                            -      8900.000 12990.000
                             Manual         5.0    4990.000  8091.000
                                            6.0     120.000  7450.000
                                            -      5300.000  7800.000
                             Semi-automatic 1.0   11000.000 11000.000
                                            5.0    9950.000 11112.500
                                            -     11750.000 12900.000
              Opel Insignia  Automatic      6.0   21300.000 33365.000
                                            8.0   25900.000 25900.000
                                            -     13490.000 13490.000
                             Manual         6.0   10350.000 16490.000
              Renault Clio   Automatic      1.0   23990.000 23990.000
                                            5.0   14495.000 15108.750

In [ ]:
df.Gears.replace([1,2,3,4,9,50,"-"],np.nan, inplace=True)

In [ ]:
df.Gears.value_counts(dropna=False)

6.000    5822
NaN      4726
5.000    3239
7.000    1908
8.000     224
Name: Gears, dtype: int64

In [ ]:
df.groupby(["body_type","make_model","Gearing_Type"]).Gears.count()

body_type      make_model      Gearing_Type
Compact        Audi A1         Automatic         209
                               Manual            354
                               Semi-automatic      3
               Audi A3         Automatic          60
                               Manual             89
                               Semi-automatic     14
               Opel Astra      Automatic          31
                               Manual            134
                               Semi-automatic      3
               Opel Corsa      Automatic         347
                               Manual            473
                               Semi-automatic     10
               Opel Insignia   Automatic           9
                               Manual             17
               Renault Clio    Automatic          70
                               Manual            162
                               Semi-automatic      1
               Renault Espace  Automatic           3
Convertible    Audi A3         Automatic           3
                               Semi-automatic      5
Coupe          Audi A1         Manual              1
               Audi A3         Automatic           4
               Opel Astra      Automatic           1
               Opel Corsa      Automatic           1
                               Manual              9
                               Semi-automatic      1
               Opel Insignia   Manual              0
               Renault Clio    Automatic           1
               Renault Espace  Automatic           0
Off-Road       Audi A2         Manual              0
               Opel Astra      Automatic           1
               Opel Corsa      Manual              3
               Opel Insignia   Automatic           3
                               Manual              3
               Renault Clio    Automatic           1
                               Manual              1
               Renault Duster  Automatic           0
                               Manual             25
               Renault Espace  Automatic           5
                               Manual              1
Sedans         Audi A1         Automatic         424
                               Manual            603
                               Semi-automatic     53
               Audi A3         Automatic         862
                               Manual            943
                               Semi-automatic    239
               Opel Astra      Automatic         253
                               Manual            458
                               Semi-automatic      5
               Opel Corsa      Automatic         195
                               Manual            535
                               Semi-automatic     25
               Opel Insignia   Automatic         288
                               Manual            425
               Renault Clio    Automatic         202
                               Manual            547
                               Semi-automatic     38
               Renault Espace  Automatic           6
                               Manual              0
Station wagon  Audi A1         Automatic           3
                               Manual             11
               Audi A3         Automatic          46
                               Manual            105
                               Semi-automatic      1
               Opel Astra      Automatic         392
                               Manual            452
                               Semi-automatic      4
               Opel Insignia   Automatic         645
                               Manual            512
               Renault Clio    Automatic          73
                               Manual            163
                               Semi-automatic      6
               Renault Espace  Automatic          75
                               Manual              6
                               Semi-automatic      1
Transporter    Opel Corsa      Manual              7
               Renault Clio    Manual             11
               Renault Espace  Automatic          21
                               Manual              7
                               Semi-automatic     22
Van            Audi A1         Automatic           1
               Opel Corsa      Manual              0
               Opel Insignia   Manual              1
               Renault Clio    Manual              0
               Renault Espace  Automatic         406
                               Manual             51
                               Semi-automatic     12
Name: Gears, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        for group3 in list(df["Gearing_Type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2) & (df["Gearing_Type"]==group3)
            mode = list(df[cond]["Gears"].mode())
            if mode != []:
                df.loc[cond, "Gears"] = df.loc[cond, "Gears"].fillna(df[cond]["Gears"].mode()[0])
            else:
                df.loc[cond, "Gears"] = df.loc[cond, "Gears"].fillna(df["Gears"].mode()[0])

In [ ]:
df.Gears.value_counts(dropna=False)

6.000    8630
5.000    4254
7.000    2810
8.000     225
Name: Gears, dtype: int64

### Extras

In [ ]:
describe("Extras")

Column Name    :  Extras
----------------------------------------
Per_of_nulls   :  % 18.61
Num_of_nulls   :  2962
Num_of_uniques :  659
----------------------------------------
Alloy wheels                                                                                                                                   3245
NaN                                                                                                                                            2962
Alloy wheels,Touch screen                                                                                                                       697
Alloy wheels,Voice Control                                                                                                                      577
Alloy wheels,Touch screen,Voice Control                                                                                                         541
Alloy wheels,Roof rack                                                                                                                          385
Alloy wheels,Sport seats                                                                                                                        380
Roof rack                                                                                                                                       337
Alloy wheels,Catalytic Converter                                                                                                                271
Alloy wheels,Sport seats,Sport suspension                                                                                                       234
Alloy wheels,Catalytic Converter,Touch screen                                                                                                   228
Alloy wheels,Sport seats,Voice Control                                                                                                          226
Catalytic Converter                                                                                                                             224
Alloy wheels,Catalytic Converter,Voice Control                                                                                                  203
Alloy wheels,Roof rack,Touch screen,Voice Control                                                                                               192
Alloy wheels,Sport suspension                                                                                                                   177
Touch screen                                                                                                                                    169
Alloy wheels,Roof rack,Touch screen                                                                                                             164
Alloy wheels,Catalytic Converter,Touch screen,Voice Control                                                                                     132
Alloy wheels,Sport package                                                                                                                      113
Alloy wheels,Trailer hitch                                                                                                                      112
Alloy wheels,Sport suspension,Voice Control                                                                                                     110
Touch screen,Voice Control                                                                                                                      104
Alloy wheels,Sport seats,Touch screen                                                                                                            98
Alloy wheels,Sport package,Sport seats,Sport suspension                                                                                          94
Alloy wheels,Roof rack,Sport seats                                                                                                               93
Alloy wheels,Sport seats,Touch screen,Voice Control                                                                                              91
Alloy wheels,Roof rack,Sport seats,Touch screen,Voice Control                                                                                    87
Voice Control                                                                                                                                    85
Alloy wheels,Sport package,Sport seats                                                                                                           81
Alloy wheels,Sport package,Sport seats,Sport suspension,Voice Control                                                                            68
Alloy wheels,Catalytic Converter,Sport seats,Voice Control                                                                                       67
Alloy wheels,Cab or rented Car,Sport seats,Voice Control                                                                                         62
Alloy wheels,Roof rack,Voice Control                                                                                                             60
Alloy wheels,Sport seats,Sport suspension,Voice Control                                                                                          57
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Voice Control                                                                            57
Catalytic Converter,Touch screen                                                                                                                 55
Alloy wheels,Catalytic Converter,Roof rack,Touch screen                                                                                          53
Roof rack,Touch screen                                                                                                                           52
Alloy wheels,Roof rack,Ski bag,Sport seats,Touch screen,Voice Control                                                                            50
Roof rack,Touch screen,Voice Control                                                                                                             49
Alloy wheels,Roof rack,Trailer hitch                                                                                                             47
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                 46
Alloy wheels,Shift paddles                                                                                                                       45
Alloy wheels,Roof rack,Sport seats,Touch screen                                                                                                  38
Alloy wheels,Sport package,Sport seats,Voice Control                                                                                             38
Cab or rented Car                                                                                                                                37
Alloy wheels,Catalytic Converter,Sport seats,Sport suspension,Voice Control                                                                      34
Catalytic Converter,Touch screen,Voice Control                                                                                                   34
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension,Voice Control                                                        33
Roof rack,Voice Control                                                                                                                          33
Alloy wheels,Cab or rented Car                                                                                                                   32
Alloy wheels,Roof rack,Ski bag,Touch screen,Voice Control                                                                                        32
Alloy wheels,Catalytic Converter,Roof rack,Sport seats,Touch screen,Voice Control                                                                32
Alloy wheels,Roof rack,Sport suspension                                                                                                          31
Alloy wheels,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                               31
Alloy wheels,Roof rack,Touch screen,Trailer hitch,Voice Control                                                                                  31
Sport suspension                                                                                                                                 30
Alloy wheels,Catalytic Converter,Sport seats,Touch screen,Voice Control                                                                          30
Trailer hitch                                                                                                                                    30
Alloy wheels,Catalytic Converter,Roof rack                                                                                                       29
Alloy wheels,Catalytic Converter,Roof rack,Voice Control                                                                                         29
Sport seats                                                                                                                                      28
Alloy wheels,Catalytic Converter,Sport seats                                                                                                     26
Roof rack,Sport seats                                                                                                                            25
Alloy wheels,Sport package,Voice Control                                                                                                         25
Alloy wheels,Catalytic Converter,Sport seats,Sport suspension                                                                                    24
Alloy wheels,Sport package,Sport seats,Touch screen,Voice Control                                                                                24
Alloy wheels,Catalytic Converter,Shift paddles,Voice Control                                                                                     24
Roof rack,Trailer hitch                                                                                                                          23
Alloy wheels,Roof rack,Sport seats,Sport suspension,Trailer hitch,Voice Control                                                                  23
Alloy wheels,Roof rack,Sport seats,Sport suspension                                                                                              23
Alloy wheels,Cab or rented Car,Sport seats                                                                                                       22
Catalytic Converter,Voice Control                                                                                                                22
Alloy wheels,Winter tyres                                                                                                                        21
Alloy wheels,Shift paddles,Touch screen,Voice Control                                                                                            21
Roof rack,Sport seats,Touch screen,Voice Control                                                                                                 20
Catalytic Converter,Roof rack,Touch screen,Voice Control                                                                                         19
Alloy wheels,Roof rack,Sport seats,Sport suspension,Touch screen,Voice Control                                                                   19
Sport seats,Sport suspension                                                                                                                     19
Alloy wheels,Roof rack,Sport package,Sport seats                                                                                                 19
Catalytic Converter,Roof rack                                                                                                                    19
Alloy wheels,Touch screen,Trailer hitch,Voice Control                                                                                            18
Alloy wheels,Sport package,Touch screen,Voice Control                                                                                            18
Sport seats,Touch screen,Voice Control                                                                                                           18
Alloy wheels,Shift paddles,Sport suspension                                                                                                      18
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                     17
Alloy wheels,Roof rack,Sport seats,Touch screen,Trailer hitch,Voice Control                                                                      17
Alloy wheels,Trailer hitch,Voice Control                                                                                                         17
Alloy wheels,Catalytic Converter,Sport package                                                                                                   17
Alloy wheels,Shift paddles,Voice Control                                                                                                         16
Alloy wheels,Shift paddles,Sport seats                                                                                                           16
Alloy wheels,Catalytic Converter,Sport package,Sport seats                                                                                       16
Alloy wheels,Cab or rented Car,Catalytic Converter                                                                                               15
Alloy wheels,Roof rack,Sport seats,Voice Control                                                                                                 14
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension                                                                      14
Catalytic Converter,Roof rack,Touch screen                                                                                                       13
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension,Touch screen,Trailer hitch,Voice Control                                       13
Alloy wheels,Roof rack,Shift paddles                                                                                                             13
Alloy wheels,Roof rack,Sport seats,Trailer hitch                                                                                                 13
Alloy wheels,Ski bag,Sport seats,Touch screen,Voice Control                                                                                      13
Alloy wheels,Sport package,Sport suspension,Voice Control                                                                                        13
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Trailer hitch,Voice Control                                                              12
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Voice Control                                                              12
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Touch screen,Voice Control                                                            12
Catalytic Converter,Roof rack,Voice Control                                                                                                      12
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension                                                                                12
Alloy wheels,Touch screen,Trailer hitch                                                                                                          12
Winter tyres                                                                                                                                     12
Alloy wheels,Roof rack,Sport seats,Sport suspension,Touch screen,Trailer hitch,Voice Control                                                     11
Alloy wheels,Catalytic Converter,Sport seats,Touch screen                                                                                        11
Alloy wheels,Ski bag,Touch screen,Voice Control                                                                                                  11
Alloy wheels,Sport package,Sport seats,Sport suspension,Touch screen                                                                             11
Alloy wheels,Catalytic Converter,Sport suspension                                                                                                11
Alloy wheels,Catalytic Converter,Sport package,Touch screen,Voice Control                                                                        11
Alloy wheels,Catalytic Converter,Shift paddles,Touch screen,Voice Control                                                                        11
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension                                                                            11
Alloy wheels,Sport package,Sport suspension                                                                                                      10
Alloy wheels,Sport seats,Trailer hitch                                                                                                           10
Alloy wheels,Sport seats,Sport suspension,Trailer hitch                                                                                          10
Alloy wheels,Catalytic Converter,Winter tyres                                                                                                    10
Alloy wheels,Sport suspension,Touch screen,Voice Control                                                                                         10
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Voice Control                                                                         10
Sport package                                                                                                                                    10
Alloy wheels,Shift paddles,Sport seats,Sport suspension                                                                                          10
Alloy wheels,Roof rack,Shift paddles,Touch screen,Voice Control                                                                                  10
Alloy wheels,Cab or rented Car,Touch screen,Voice Control                                                                                         9
Alloy wheels,Cab or rented Car,Touch screen                                                                                                       9
Alloy wheels,Roof rack,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                        9
Alloy wheels,Roof rack,Touch screen,Trailer hitch                                                                                                 9
Alloy wheels,Cab or rented Car,Roof rack                                                                                                          9
Alloy wheels,Catalytic Converter,Trailer hitch                                                                                                    9
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen                                                                8

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Extras"].mode())
            if mode != []:
                df.loc[cond, "Extras"] = df.loc[cond, "Extras"].fillna(df[cond]["Extras"].mode()[0])
            else:
                df.loc[cond, "Extras"] = df.loc[cond, "Extras"].fillna(df["Extras"].mode()[0])

In [ ]:
df.Extras.value_counts(dropna=False)

Alloy wheels                                                                                                                                   5786
Alloy wheels,Touch screen                                                                                                                       697
Roof rack                                                                                                                                       596
Alloy wheels,Voice Control                                                                                                                      582
Alloy wheels,Touch screen,Voice Control                                                                                                         544
Alloy wheels,Roof rack                                                                                                                          529
Alloy wheels,Sport seats                                                                                                                        382
Alloy wheels,Catalytic Converter                                                                                                                275
Alloy wheels,Sport seats,Sport suspension                                                                                                       234
Alloy wheels,Catalytic Converter,Touch screen                                                                                                   228
Alloy wheels,Sport seats,Voice Control                                                                                                          226
Catalytic Converter                                                                                                                             224
Alloy wheels,Catalytic Converter,Voice Control                                                                                                  203
Alloy wheels,Roof rack,Touch screen,Voice Control                                                                                               192
Alloy wheels,Sport suspension                                                                                                                   177
Touch screen                                                                                                                                    169
Alloy wheels,Roof rack,Touch screen                                                                                                             164
Alloy wheels,Catalytic Converter,Touch screen,Voice Control                                                                                     132
Alloy wheels,Sport package                                                                                                                      113
Alloy wheels,Trailer hitch                                                                                                                      112
Alloy wheels,Sport suspension,Voice Control                                                                                                     110
Touch screen,Voice Control                                                                                                                      104
Alloy wheels,Sport seats,Touch screen                                                                                                            98
Alloy wheels,Sport package,Sport seats,Sport suspension                                                                                          94
Alloy wheels,Roof rack,Sport seats                                                                                                               93
Alloy wheels,Sport seats,Touch screen,Voice Control                                                                                              91
Alloy wheels,Roof rack,Sport seats,Touch screen,Voice Control                                                                                    87
Voice Control                                                                                                                                    85
Alloy wheels,Sport package,Sport seats                                                                                                           81
Alloy wheels,Sport package,Sport seats,Sport suspension,Voice Control                                                                            68
Alloy wheels,Catalytic Converter,Sport seats,Voice Control                                                                                       67
Alloy wheels,Cab or rented Car,Sport seats,Voice Control                                                                                         62
Alloy wheels,Roof rack,Voice Control                                                                                                             60
Alloy wheels,Sport seats,Sport suspension,Voice Control                                                                                          57
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Voice Control                                                                            57
Catalytic Converter,Touch screen                                                                                                                 55
Alloy wheels,Catalytic Converter,Roof rack,Touch screen                                                                                          53
Roof rack,Touch screen                                                                                                                           52
Alloy wheels,Roof rack,Ski bag,Sport seats,Touch screen,Voice Control                                                                            50
Roof rack,Touch screen,Voice Control                                                                                                             49
Alloy wheels,Roof rack,Trailer hitch                                                                                                             47
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                 46
Alloy wheels,Shift paddles                                                                                                                       45
Alloy wheels,Sport package,Sport seats,Voice Control                                                                                             38
Alloy wheels,Roof rack,Sport seats,Touch screen                                                                                                  38
Cab or rented Car                                                                                                                                37
Catalytic Converter,Touch screen,Voice Control                                                                                                   34
Alloy wheels,Catalytic Converter,Sport seats,Sport suspension,Voice Control                                                                      34
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension,Voice Control                                                        33
Roof rack,Voice Control                                                                                                                          33
Alloy wheels,Catalytic Converter,Roof rack,Sport seats,Touch screen,Voice Control                                                                32
Alloy wheels,Roof rack,Ski bag,Touch screen,Voice Control                                                                                        32
Alloy wheels,Cab or rented Car                                                                                                                   32
Alloy wheels,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                               31
Alloy wheels,Roof rack,Sport suspension                                                                                                          31
Alloy wheels,Roof rack,Touch screen,Trailer hitch,Voice Control                                                                                  31
Alloy wheels,Catalytic Converter,Sport seats,Touch screen,Voice Control                                                                          30
Sport suspension                                                                                                                                 30
Trailer hitch                                                                                                                                    30
Alloy wheels,Catalytic Converter,Roof rack,Voice Control                                                                                         29
Alloy wheels,Catalytic Converter,Roof rack                                                                                                       29
Sport seats                                                                                                                                      28
Alloy wheels,Catalytic Converter,Sport seats                                                                                                     26
Alloy wheels,Sport package,Voice Control                                                                                                         25
Roof rack,Sport seats                                                                                                                            25
Alloy wheels,Catalytic Converter,Shift paddles,Voice Control                                                                                     24
Alloy wheels,Sport package,Sport seats,Touch screen,Voice Control                                                                                24
Alloy wheels,Catalytic Converter,Sport seats,Sport suspension                                                                                    24
Alloy wheels,Roof rack,Sport seats,Sport suspension                                                                                              23
Alloy wheels,Roof rack,Sport seats,Sport suspension,Trailer hitch,Voice Control                                                                  23
Roof rack,Trailer hitch                                                                                                                          23
Alloy wheels,Cab or rented Car,Sport seats                                                                                                       22
Catalytic Converter,Voice Control                                                                                                                22
Alloy wheels,Winter tyres                                                                                                                        21
Alloy wheels,Shift paddles,Touch screen,Voice Control                                                                                            21
Roof rack,Sport seats,Touch screen,Voice Control                                                                                                 20
Catalytic Converter,Roof rack,Touch screen,Voice Control                                                                                         19
Catalytic Converter,Roof rack                                                                                                                    19
Alloy wheels,Roof rack,Sport seats,Sport suspension,Touch screen,Voice Control                                                                   19
Sport seats,Sport suspension                                                                                                                     19
Alloy wheels,Roof rack,Sport package,Sport seats                                                                                                 19
Sport seats,Touch screen,Voice Control                                                                                                           18
Alloy wheels,Sport package,Touch screen,Voice Control                                                                                            18
Alloy wheels,Touch screen,Trailer hitch,Voice Control                                                                                            18
Alloy wheels,Shift paddles,Sport suspension                                                                                                      18
Alloy wheels,Roof rack,Sport seats,Touch screen,Trailer hitch,Voice Control                                                                      17
Alloy wheels,Trailer hitch,Voice Control                                                                                                         17
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                                     17
Alloy wheels,Catalytic Converter,Sport package                                                                                                   17
Alloy wheels,Shift paddles,Voice Control                                                                                                         16
Alloy wheels,Shift paddles,Sport seats                                                                                                           16
Alloy wheels,Catalytic Converter,Sport package,Sport seats                                                                                       16
Alloy wheels,Cab or rented Car,Catalytic Converter                                                                                               15
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension                                                                      14
Alloy wheels,Roof rack,Sport seats,Voice Control                                                                                                 14
Alloy wheels,Ski bag,Sport seats,Touch screen,Voice Control                                                                                      13
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension,Touch screen,Trailer hitch,Voice Control                                       13
Alloy wheels,Roof rack,Sport seats,Trailer hitch                                                                                                 13
Alloy wheels,Roof rack,Shift paddles                                                                                                             13
Alloy wheels,Sport package,Sport suspension,Voice Control                                                                                        13
Catalytic Converter,Roof rack,Touch screen                                                                                                       13
Alloy wheels,Touch screen,Trailer hitch                                                                                                          12
Catalytic Converter,Roof rack,Voice Control                                                                                                      12
Winter tyres                                                                                                                                     12
Alloy wheels,Catalytic Converter,Roof rack,Touch screen,Trailer hitch,Voice Control                                                              12
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Voice Control                                                              12
Alloy wheels,Roof rack,Sport package,Sport seats,Sport suspension                                                                                12
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Touch screen,Voice Control                                                            12
Alloy wheels,Sport package,Sport seats,Sport suspension,Touch screen                                                                             11
Alloy wheels,Ski bag,Touch screen,Voice Control                                                                                                  11
Alloy wheels,Catalytic Converter,Sport package,Touch screen,Voice Control                                                                        11
Alloy wheels,Catalytic Converter,Shift paddles,Touch screen,Voice Control                                                                        11
Alloy wheels,Catalytic Converter,Sport seats,Touch screen                                                                                        11
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension                                                                            11
Alloy wheels,Catalytic Converter,Sport suspension                                                                                                11
Alloy wheels,Roof rack,Sport seats,Sport suspension,Touch screen,Trailer hitch,Voice Control                                                     11
Alloy wheels,Sport seats,Sport suspension,Trailer hitch                                                                                          10
Alloy wheels,Sport seats,Trailer hitch                                                                                                           10
Alloy wheels,Shift paddles,Sport seats,Sport suspension                                                                                          10
Alloy wheels,Catalytic Converter,Winter tyres                                                                                                    10
Alloy wheels,Sport package,Sport suspension                                                                                                      10
Alloy wheels,Roof rack,Shift paddles,Touch screen,Voice Control                                                                                  10
Alloy wheels,Catalytic Converter,Sport package,Sport seats,Voice Control                                                                         10
Alloy wheels,Sport suspension,Touch screen,Voice Control                                                                                         10
Sport package                                                                                                                                    10
Alloy wheels,Cab or rented Car,Roof rack                                                                                                          9
Alloy wheels,Cab or rented Car,Touch screen                                                                                                       9
Alloy wheels,Catalytic Converter,Trailer hitch                                                                                                    9
Alloy wheels,Cab or rented Car,Touch screen,Voice Control                                                                                         9
Alloy wheels,Roof rack,Touch screen,Trailer hitch                                                                                                 9
Alloy wheels,Roof rack,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen,Voice Control                                        9
Alloy wheels,Catalytic Converter,Sport package,Sport suspension,Voice Control                                                                     8
Roof rack,Sport seats,Touch screen                                                                                                                8
Alloy wheels,Shift paddles,Sport package,Sport seats,Sport suspension,Touch screen                                                                8
Alloy wheels,Sport suspension,Touch screen                                                                                                        8

### Previous_Owners

In [ ]:
describe("Previous_Owners")

Column Name    :  Previous_Owners
----------------------------------------
Per_of_nulls   :  % 41.71
Num_of_nulls   :  6640
Num_of_uniques :  5
----------------------------------------
1.000    8294
NaN      6640
2.000     778
0.000     188
3.000      17
4.000       2
Name: Previous_Owners, dtype: int64

In [ ]:
df.Previous_Owners.fillna("-", inplace=True)

In [ ]:
df.groupby(["Previous_Owners", "age"]).km.describe()

                         count      mean       std       min       25%  \
Previous_Owners age
0.0             0.000  164.000   785.343   837.357     0.000     6.750
                1.000    8.000 27179.375  8253.035 15000.000 21807.750
                2.000    6.000 56883.667 23572.241 19300.000 45500.000
                3.000   10.000 60492.900 20985.402 23580.000 52530.250
1.0             0.000 1583.000  2118.980  4038.598     1.000    10.000
                1.000 2972.000 17995.812 10621.121     1.000  9962.250
                2.000 1711.000 42925.590 30881.155     1.000 21068.500
                3.000 2028.000 83265.577 41452.815    10.000 52175.000
2.0             0.000   10.000  8865.000 23817.262    10.000    15.000
                1.000   75.000 16729.173  9910.780    50.000  9750.000
                2.000  296.000 30664.311 18980.036    15.000 17768.000
                3.000  397.000 56134.713 31651.648  1800.000 36934.000
3.0             2.000    7.000 39957.857 19237.062 17390.000 25595.000
                3.000   10.000 54629.900 25500.682 27600.000 40500.000
4.0             2.000    1.000 19700.000       NaN 19700.000 19700.000
                3.000    1.000 57000.000       NaN 57000.000 57000.000
-               0.000 2673.000  1397.471  4257.705     1.000    10.000
                1.000 1478.000 18024.123 11792.622     1.000 10040.000
                2.000 1256.000 42711.471 25798.711     1.000 24000.000
                3.000 1233.000 75087.171 34683.096    35.000 48597.000

                            50%        75%        max
Previous_Owners age
0.0             0.000   100.000   1520.636   2493.427
                1.000 28800.000  32750.000  37592.000
                2.000 64000.000  67501.500  86000.000
                3.000 62000.000  64875.000  91883.000
1.0             0.000    65.000   3037.000  88000.000
                1.000 18000.000  25272.250 113392.000
                2.000 33943.000  58716.500 317000.000
                3.000 80049.500 110000.000 291800.000
2.0             0.000   297.500   2500.000  76300.000
                1.000 15455.000  25066.000  47000.000
                2.000 23222.500  45050.000 116184.000
                3.000 49351.000  68550.000 229500.000
3.0             2.000 37125.000  54000.000  66000.000
                3.000 50750.000  62524.250 116000.000
4.0             2.000 19700.000  19700.000  19700.000
                3.000 57000.000  57000.000  57000.000
-               0.000   100.000   1520.636 127022.000
                1.000 17378.500  24500.000 136000.000
                2.000 37527.000  55000.000 240000.000
                3.000 73130.000  97000.000 248000.000

In [ ]:
df.Previous_Owners.replace("-",1, inplace=True)

In [ ]:
df.Previous_Owners.value_counts(dropna=False)

1.000    14934
2.000      778
0.000      188
3.000       17
4.000        2
Name: Previous_Owners, dtype: int64

### hp_kW

In [ ]:
describe("hp_kW")

Column Name    :  hp_kW
----------------------------------------
Per_of_nulls   :  % 0.55
Num_of_nulls   :  88
Num_of_uniques :  80
----------------------------------------
85.000     2542
66.000     2122
81.000     1402
100.000    1308
110.000    1112
70.000      888
125.000     707
51.000      695
55.000      569
118.000     516
92.000      466
121.000     392
147.000     380
77.000      345
56.000      286
54.000      276
103.000     253
87.000      232
165.000     194
88.000      177
60.000      160
162.000      98
NaN          88
74.000       81
96.000       72
71.000       59
101.000      47
67.000       40
154.000      39
122.000      35
119.000      30
164.000      27
135.000      24
82.000       22
52.000       22
78.000       20
1.000        20
294.000      18
146.000      18
141.000      16
57.000       10
104.000       8
120.000       8
191.000       7
112.000       7
155.000       6
117.000       6
184.000       5
90.000        4
76.000        4
65.000        4
149.000       3
80.000        3
168.000       3
98.000        3
93.000        3
228.000       2
270.000       2
53.000        2
140.000       2
86.000        2
167.000       2
127.000       2
89.000        2
143.000       2
63.000        2
40.000        2
150.000       2
163.000       1
115.000       1
132.000       1
75.000        1
4.000         1
137.000       1
123.000       1
133.000       1
84.000        1
195.000       1
44.000        1
239.000       1
9.000         1
Name: hp_kW, dtype: int64

In [ ]:
df.hp_kW.fillna("-", inplace=True)

In [ ]:
df.groupby(["body_type", "make_model", "hp_kW"]).price.describe()

                                      count      mean       std       min  \
body_type     make_model     hp_kW
Compact       Audi A1        60.0    58.000 15189.828  1663.611 10900.000
                             66.0   162.000 15398.210  1934.301 10490.000
                             70.0   332.000 17983.262  3315.814  9950.000
                             71.0    32.000 20831.594  2410.840 15890.000
                             85.0   330.000 22604.103  4572.568 11100.000
                             86.0     1.000 14295.000       NaN 14295.000
                             92.0    90.000 18029.056  3027.431 12550.000
                             93.0     2.000 21447.500   774.282 20900.000
                             110.0   20.000 23620.450  3777.344 15490.000
                             141.0    2.000 22495.000   841.457 21900.000
                             147.0    8.000 28797.125   355.356 28200.000
                             -        2.000 19125.000  5126.524 15500.000
              Audi A3        81.0    50.000 17147.920  2283.775 12900.000
                             82.0    11.000 17042.091  1353.481 14450.000
                             85.0    53.000 22656.717  6328.251 13790.000
                             87.0     3.000 22195.000   349.887 21990.000
                             92.0    43.000 13824.884   984.708 13100.000
                             110.0   15.000 25249.333  7908.351 13990.000
                             112.0    1.000 17894.000       NaN 17894.000
                             135.0    3.000 15950.000     0.000 15950.000
                             150.0    1.000 24950.000       NaN 24950.000
                             294.0    1.000 67600.000       NaN 67600.000
                             -        1.000 18700.000       NaN 18700.000
              Opel Astra     66.0     5.000 13899.000     0.000 13899.000
                             70.0     1.000 11980.000       NaN 11980.000
                             76.0     3.000 18783.333   288.675 18450.000
                             77.0    28.000 16603.607  2778.069  9700.000
                             78.0     4.000 13995.000  1080.123 12495.000
                             81.0    79.000 13886.291  2273.141  9000.000
                             82.0     3.000 10645.000   264.150 10490.000
                             92.0    20.000 13749.250  2424.930 11790.000
                             100.0   17.000 13883.588  3213.235  8450.000
                             101.0    1.000 16499.000       NaN 16499.000
                             110.0   16.000 24795.438  7171.278 10900.000
                             147.0    7.000 36260.000  2968.213 30900.000
                             -        1.000 31246.000       NaN 31246.000
              Opel Corsa     40.0     1.000  7650.000       NaN  7650.000
                             44.0     1.000 12435.000       NaN 12435.000
                             51.0   334.000  9420.856  1605.821  6290.000
                             55.0    46.000  8270.630  1352.503  5300.000
                             65.0     3.000 14950.000     0.000 14950.000
                             66.0   890.000 12814.280  2907.180   120.000
                             70.0    27.000  8033.259  1259.786  6380.000
                             71.0     3.000  9283.000  1560.166  7950.000
                             74.0    12.000  9675.000  1115.270  7190.000
                             88.0     1.000  7700.000       NaN  7700.000
                             -        1.000 10350.000       NaN 10350.000
              Opel Insignia  100.0    8.000 18523.750  3057.440 13900.000
                             103.0    2.000 10350.000     0.000 10350.000
                             104.0    1.000 40533.000       NaN 40533.000
                             121.0    7.000 35453.714  4424.540 26990.000
                             125.0    2.000 19695.000  8775.195 13490.000
                             147.0    7.000 39277.571  4942.583 35490.000
              Renault Clio   4.0      1.000  8990.000       NaN  8990.000
                             40.0     1.000  5890.000       NaN  5890.000
                             54.0    38.000  9771.105   966.152  6800.000
                             55.0   105.000  9083.000  1405.494  5800.000
                             56.0   109.000 10929.514   476.163  9545.000
                             57.0    10.000 11332.000   123.450 10990.000
                             66.0    30.000 12337.900  4650.772  6200.000
                             87.0   104.000 15108.673  1845.042 10800.000
                             88.0    48.000 15272.188  1938.629 12545.000
                             90.0     4.000 17655.000  6094.924 13950.000
                             147.0    9.000 20142.111  2560.899 15990.000
                             162.0   16.000 24710.375  3556.513 13990.000
                             163.0    1.000 29740.000       NaN 29740.000
                             -        8.000 15797.500  1040.271 14290.000
              Renault Espace 118.0    2.000 27700.000  8202.439 21900.000
                             119.0    1.000 23990.000       NaN 23990.000
                             147.0    2.000 30450.000 17748.380 17900.000
                             165.0    1.000 39990.000       NaN 39990.000
Convertible   Audi A3        81.0     1.000 20900.000       NaN 20900.000
                             110.0    5.000 24848.600  9248.721 10893.000
                             135.0    1.000 22000.000       NaN 22000.000
                             228.0    1.000 56100.000       NaN 56100.000
Coupe         Audi A1        70.0     1.000 13950.000       NaN 13950.000
                             85.0     1.000 15900.000       NaN 15900.000
              Audi A3        81.0     3.000 17326.667   583.124 16990.000
                             85.0     1.000 19000.000       NaN 19000.000
              Opel Astra     103.0    1.000 14490.000       NaN 14490.000
                             110.0    1.000 29990.000       NaN 29990.000
              Opel Corsa     51.0     5.000  8680.000  1473.771  7200.000
                             55.0     3.000  7833.333   850.490  7200.000
                             66.0     3.000  9613.333  2349.901  6900.000
                             70.0     1.000 10500.000       NaN 10500.000
                             85.0     1.000  7800.000       NaN  7800.000
              Opel Insignia  81.0     1.000 17094.000       NaN 17094.000
              Renault Clio   147.0    1.000 17990.000       NaN 17990.000
              Renault Espace 118.0    1.000 26994.000       NaN 26994.000
                             165.0    1.000 34140.000       NaN 34140.000
Off-Road      Audi A2        85.0     1.000 28200.000       NaN 28200.000
              Opel Astra     110.0    1.000 18590.000       NaN 18590.000
              Opel Corsa     66.0     2.000  7900.000     0.000  7900.000
                             74.0     1.000  8700.000       NaN  8700.000
              Opel Insignia  122.0    1.000 33490.000       NaN 33490.000
                             125.0    4.000 26387.000  9267.565 12750.000
                             147.0    1.000 32345.000       NaN 32345.000
                             155.0    1.000 34776.000       NaN 34776.000
              Renault Clio   55.0     1.000  7700.000       NaN  7700.000
                             87.0     1.000 17990.000       NaN 17990.000
              Renault Duster 77.0    25.000 12827.760  1441.582 10850.000
                             81.0     1.000 12000.000       NaN 12000.000
                             -        8.000 14641.500  1487.576 13250.000
              Renault Espace 118.0    8.000 25762.500  5385.347 14900.000
Sedans        Audi A1        60.0    95.000 15218.168  1624.267 11900.000
                             66.0   296.000 15922.797  2331.608 10800.000
                             67.0    12.000 15432.417  2778.191 11990.000
                             70.0   455.000 17282.068  3210.456  8999.000
                             71.0    24.000 19177.250  2539.495 14390.000
                             85.0   555.000 21609.523  4822.007 10000.000
                             87.0     4.000 14865.000   750.000 14490.000
                             92.0    79.000 19078.975  2790.209 13000.000
                             93.0     1.000 17900.000       NaN 17900.000
                             110.0    9.000 22591.333  4188.635 16999.000
                             112.0    1.000 18399.000       NaN 18399.000
                             140.0    1.000 23490.000       NaN 23490.000
                             141.0   14.000 21232.000  2597.466 14500.000
                             147.0    5.000 30729.600  4008.782 28880.000
              Audi A3        9.0      1.000 20440.000       NaN 20440.000
                             81.0   675.000 17216.644  2424.455 10550.000
                             82.0     4.000 18055.000  1130.000 17490.000
                             85.0  1419.000 22432.328  2492.568 15699.000
                             86.0     1.000 17900.000       NaN 17900.000
                             87.0     3.000 17690.000     0.000 17690.000
                             92.0    44.000 16013.136  1247.480 14900.000
                             96.0     9.000 28236.444  3815.422 24300.000
                             100.0    1.000 15950.000       NaN 15950.000
                             110.0  420.000 21923.893  4832.669 12500.000
                             132.0    1.000 14990.000       NaN 14990.000
                             133.0    1.000 19500.000       NaN 19500.000
                             135.0   20.000 24835.300  7496.991 14990.000
                             137.0    1.000 21990.000       NaN 21990.000
                             140.0    1.000 25600.000       NaN 25600.000
                             162.0    1.000 25000.000       NaN 25000.000
                             228.0    1.000 58990.000       NaN 58990.000
                             270.0    2.000 41750.000  1060.660 41000.000
                             294.0   16.000 55736.812  6989.238 45890.000
              Opel Astra     1.0      4.000 11700.000     0.000 11700.000
                             60.0     4.000  9760.000   888.107  8900.000
                             66.0    57.000 16465.193  1521.361 13479.000
                             70.0    16.000 12554.688  2770.431  9290.000
                             74.0    54.000 12013.889  1433.342  9990.000
                             77.0   223.000 15195.547  2330.367  8860.000
                             78.0    12.000 14630.250  1775.260 12500.000
                             80.0     2.000 11400.000   141.421 11300.000
                             81.0   168.000 12169.869  2413.296  6950.000
                             85.0     6.000 13921.667  3028.421 10750.000
                             88.0     1.000 12500.000       NaN 12500.000
                             92.0   110.000 15825.182  2210.907 10400.000
                             100.0   91.000 15748.044  4315.880  6500.000
                             101.0    4.000 20624.250  5398.088 15900.000
                             103.0    1.000 14600.000       NaN 14600.000
                             110.0  273.000 19241.740  4379.750 10450.000
                             112.0    3.000 22920.000  6011.048 15980.000
                             118.0    1.000 10950.000       NaN 10950.000
                             147.0   21.000 26579.714  5129.017 17990.000
                             149.0    1.000 27690.000       NaN 27690.000
                             -        1.000 18200.000       NaN 18200.000
              Opel Corsa     1.0      7.000  8300.000     0.000  8300.000
                             51.0   351.000  8975.707  1359.550  5950.000
                             52.0    22.000  8164.136   735.112  7179.000
                             55.0   120.000  9102.450  1394.134  5499.000
                             66.0   343.000 12193.869  2881.779    13.000
                             67.0     4.000  8139.750   299.500  7990.000
                             70.0    25.000  8121.400  1364.355  4950.000
                             74.0     1.000  9590.000       NaN  9590.000
                             75.0     1.000  8500.000       NaN  8500.000
                             -        1.000 13400.000       NaN 13400.000
              Opel Insignia  81.0    16.000 21769.562  4798.891 13900.000
                             88.0    28.000 12249.500  2267.243  8600.000
                             89.0     1.000 13500.000       NaN 13500.000
                             92.0     2.000 11900.000   282.843 11700.000
                             100.0  327.000 18905.067  5573.881  9650.000
                             101.0   33.000 15522.879  3415.514 11450.000
                             103.0  139.000 18833.576  4454.879 10350.000
                             118.0    1.000 15780.000       NaN 15780.000
                             120.0    3.000 25596.333  1227.585 24257.000
                             121.0  112.000 25937.411  6107.300 18000.000
                             122.0    9.000 26312.444  2779.650 23600.000
                             125.0  156.000 22236.571  7573.781 10262.000
                             127.0    1.000 35590.000       NaN 35590.000
                             147.0   43.000 33509.674  4706.422 25415.000
                             149.0    1.000 35999.000       NaN 35999.000
                             154.0   14.000 36994.857  2301.215 33599.000
                             155.0    2.000 34991.000     0.000 34991.000
                             184.0    2.000 18890.000  1272.792 17990.000
                             191.0    4.000 30166.000 12531.272 11600.000
                             -        6.000 22385.000 13014.327 13490.000
              Renault Clio   53.0     1.000  7990.000       NaN  7990.000
                             54.0   143.000  9428.070   957.753  6500.000
                             55.0   248.000  8863.702  1272.557  5445.000
                             56.0   142.000 10479.014   880.012  7490.000
                             66.0   182.000 11420.005  2895.394  6250.000
                             67.0    16.000 14665.625  2970.780  7990.000
                             74.0     1.000 10390.000       NaN 10390.000
                             81.0     2.000 10550.000  1767.767  9300.000
                             87.0    84.000 15258.083  1888.577 10500.000
                             88.0    30.000 14960.700  1809.516 10950.000
                             147.0    7.000 19911.143  2302.424 16998.000
                             162.0   81.000 23014.185  3144.345 15000.000
                             164.0   27.000 18490.000     0.000 18490.000
                             -       20.000  7831.000   656.569  6900.000
              Renault Espace 1.0      2.000 23800.000     0.000 23800.000
                             96.0     2.000 21494.500  3529.170 18999.000
                             118.0   11.000 28344.182  2552.223 25490.000
                             147.0    4.000 40584.000 10300.334 25900.000
                             165.0    2.000 33195.000  5239.661 29490.000
Station wagon Audi A1        60.0     3.000 15106.667  1890.882 12950.000
                             66.0     7.000 16018.429  1779.762 13999.000
                             70.0     3.000 17420.000  3283.474 14440.000
                             85.0     4.000 22702.750  7207.560 16422.000
                             92.0     3.000 17623.000  3738.860 13979.000
                             110.0    1.000 20650.000       NaN 20650.000
              Audi A3        81.0    56.000 16533.857  2672.559 11790.000
                             85.0   156.000 22130.917  2565.788 15850.000
                             92.0     6.000 17247.500  1321.559 14995.000
                             110.0   63.000 20433.079  4921.056  5555.000
                             294.0    1.000 63900.000       NaN 63900.000
              Opel Astra     1.0      3.000 11700.000   173.205 11600.000
                             66.0    16.000 17109.062   920.084 15285.000
                             67.0     2.000 15990.000   565.685 15590.000
                             70.0    27.000 10323.444  1311.417  8200.000
                             74.0    12.000 10534.667  1718.311  9400.000
                             76.0     1.000 15950.000       NaN 15950.000
                             77.0    69.000 15592.029  2468.365  8740.000
                             78.0     4.000 16735.500  2196.539 13450.000
                             80.0     1.000  6900.000       NaN  6900.000
                             81.0   332.000 11530.232  2458.924  6480.000
                             82.0     4.000 12246.250   919.976 10900.000
                             84.0     1.000 10480.000       NaN 10480.000
                             85.0    15.000 10685.933   747.872  9500.000
                             88.0     1.000  8950.000       NaN  8950.000
                             92.0    69.000 16708.768  2073.627 11950.000
                             100.0  382.000 15275.534  4011.910   255.000
                             101.0    2.000 15320.000  3634.529 12750.000
                             103.0   12.000 13360.250  2020.410  9290.000
                             110.0  288.000 20069.115  3873.404 14000.000
                             112.0    2.000 26244.500   347.189 25999.000
                             118.0    5.000 10782.000  2584.158  7990.000
                             147.0   37.000 29603.378  3524.758 23150.000
              Opel Insignia  1.0      4.000 15850.000   635.085 15300.000
                             81.0    17.000 25008.471  5053.532 17480.000
                             88.0    46.000 13103.848  2138.462  8290.000
                             89.0     1.000 14900.000       NaN 14900.000
                             100.0  482.000 17851.465  6532.889  8913.000
                             101.0    7.000 18889.714  7410.861 12990.000
                             103.0   98.000 18779.694  3736.562 12450.000
                             104.0    7.000 24700.143  2456.258 23349.000
                             120.0    4.000 17290.500  5879.364 12900.000
                             121.0  272.000 24103.551  4934.824 17489.000
                             122.0   25.000 26986.480  4722.675 19450.000
                             123.0    1.000 31459.000       NaN 31459.000
                             125.0  545.000 20705.077  7036.072  9500.000
                             127.0    1.000 21990.000       NaN 21990.000
                             143.0    2.000 15970.000  1442.498 14950.000
                             146.0    1.000 39490.000       NaN 39490.000
                             147.0  109.000 34490.055  4121.431 25375.000
                             154.0   25.000 37412.480  1667.876 33450.000
                             155.0    3.000 35847.000   569.845 35189.000
                             184.0    3.000 17429.667   811.868 16500.000
                             191.0    3.000 34120.000  2902.895 30800.000
                             195.0    1.000 11980.000       NaN 11980.000
                             239.0    1.000 17990.000       NaN 17990.000
                             -        4.000 14142.500  2408.255 10600.000
              Renault Clio   53.0     1.000  9450.000       NaN  9450.000
                             54.0    93.000  9192.043   735.426  6900.000
                             55.0    34.000  8607.853  1385.114  6000.000
                             56.0    20.000 10966.200   733.875  9170.000

In [ ]:
df.hp_kW.replace("-", np.nan, inplace=True)

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["hp_kW"].mode())
            if mode != []:
                df.loc[cond, "hp_kW"] = df.loc[cond, "hp_kW"].fillna(df[cond]["hp_kW"].mode()[0])
            else:
                df.loc[cond, "hp_kW"] = df.loc[cond, "hp_kW"].fillna(df["hp_kW"].mode()[0])

In [ ]:
df.hp_kW.value_counts(dropna=False)

85.000     2543
66.000     2124
81.000     1403
100.000    1314
110.000    1113
70.000      890
125.000     711
51.000      696
55.000      589
118.000     550
92.000      466
121.000     392
147.000     380
77.000      353
56.000      294
54.000      276
103.000     253
87.000      232
165.000     194
88.000      177
60.000      160
162.000      98
74.000       81
96.000       72
71.000       59
101.000      47
67.000       40
154.000      39
122.000      35
119.000      30
164.000      27
135.000      24
52.000       22
82.000       22
1.000        20
78.000       20
294.000      18
146.000      18
141.000      16
57.000       10
120.000       8
104.000       8
112.000       7
191.000       7
155.000       6
117.000       6
184.000       5
65.000        4
90.000        4
76.000        4
168.000       3
98.000        3
149.000       3
80.000        3
93.000        3
167.000       2
228.000       2
53.000        2
143.000       2
150.000       2
140.000       2
270.000       2
63.000        2
40.000        2
127.000       2
86.000        2
89.000        2
163.000       1
132.000       1
115.000       1
239.000       1
4.000         1
137.000       1
133.000       1
84.000        1
123.000       1
44.000        1
195.000       1
75.000        1
9.000         1
Name: hp_kW, dtype: int64

### Inspection_new

In [ ]:
describe("Inspection_new")

Column Name    :  Inspection_new
----------------------------------------
Per_of_nulls   :  % 75.3
Num_of_nulls   :  11987
Num_of_uniques :  1
----------------------------------------
NaN    11987
Yes     3932
Name: Inspection_new, dtype: int64

In [ ]:
df.Inspection_new.fillna("-", inplace=True)

In [ ]:
df.Inspection_new.value_counts(dropna=False)

-      11987
Yes     3932
Name: Inspection_new, dtype: int64

In [ ]:
df.groupby(["body_type", "make_model", "age","Inspection_new"]).price.describe()

                                                    count      mean       std  \
body_type     make_model     age   Inspection_new
Compact       Audi A1        0.000 -              243.000 24206.370  3530.095
                                   Yes            133.000 22542.248  3076.119
                             1.000 -              150.000 19065.307  2836.071
                                   Yes            118.000 17999.517  2293.776
                             2.000 -              115.000 16425.670  1985.790
                                   Yes             46.000 17045.652  2278.592
                             3.000 -              128.000 14745.820  1877.293
                                   Yes            106.000 14275.811  1923.911
              Audi A3        0.000 -               20.000 28815.150  8160.396
                                   Yes              1.000 24900.000       NaN
                             1.000 -               29.000 22030.931  4270.469
                             2.000 -               39.000 20489.769  8208.445
                             3.000 -               90.000 15260.144  2269.181
                                   Yes              3.000 16613.333  1572.270
              Opel Astra     0.000 -               57.000 21961.579  7283.997
                                   Yes              4.000 22604.500  6174.879
                             1.000 -               39.000 14717.538  1266.385
                             2.000 -               54.000 13112.074  1895.684
                                   Yes              1.000 11980.000       NaN
                             3.000 -               24.000 11533.500  2764.322
                                   Yes              6.000 13984.667  1871.167
              Opel Corsa     0.000 -              236.000 13894.110  2910.138
                                   Yes            285.000 13573.046  2560.459
                             1.000 -              278.000 11043.342  2133.027
                                   Yes            125.000 12987.920  1476.389
                             2.000 -              133.000  9349.263  1600.873
                                   Yes             45.000 10224.822  1866.754
                             3.000 -              119.000  8616.807  2313.057
                                   Yes             98.000  8221.633  1677.433
              Opel Insignia  0.000 -               17.000 35967.765  6435.598
                             1.000 -                2.000 20400.000   707.107
                             2.000 -                4.000 17545.000  3341.262
                             3.000 -                4.000 12375.000  2373.640
              Renault Clio   0.000 -              149.000 11927.664  2832.951
                                   Yes             28.000 11385.357  2233.728
                             1.000 -               74.000 15571.959  5298.902
                                   Yes             60.000 16161.100  3564.435
                             2.000 -               81.000 12579.210  3397.424
                                   Yes              5.000 10948.000  3972.514
                             3.000 -               77.000  9314.026  2645.246
                                   Yes             10.000 11358.400  2854.724
              Renault Espace 0.000 -                3.000 38830.000  4855.070
                             2.000 -                1.000 23990.000       NaN
                             3.000 -                2.000 19900.000  2828.427
Convertible   Audi A3        1.000 -                3.000 29664.333 23557.901
                             2.000 -                4.000 28562.500  5301.159
                             3.000 -                1.000 20000.000       NaN
Coupe         Audi A1        2.000 -                1.000 15900.000       NaN
                             3.000 -                1.000 13950.000       NaN
              Audi A3        2.000 -                1.000 19000.000       NaN
                             3.000 -                3.000 17326.667   583.124
              Opel Astra     0.000 -                1.000 29990.000       NaN
                             3.000 Yes              1.000 14490.000       NaN
              Opel Corsa     0.000 -                3.000 10283.333  1286.792
                             2.000 -                4.000  8150.000   550.757
                                   Yes              1.000 10990.000       NaN
                             3.000 -                5.000  7920.000  1478.851
              Opel Insignia  2.000 -                1.000 17094.000       NaN
              Renault Clio   2.000 Yes              1.000 17990.000       NaN
              Renault Espace 0.000 -                1.000 34140.000       NaN
                             1.000 -                1.000 26994.000       NaN
Off-Road      Audi A2        1.000 -                1.000 28200.000       NaN
              Opel Astra     1.000 -                1.000 18590.000       NaN
              Opel Corsa     2.000 -                3.000  8166.667   461.880
              Opel Insignia  0.000 -                6.000 32234.833  2137.208
                             3.000 -                1.000 12750.000       NaN
              Renault Clio   0.000 -                1.000 17990.000       NaN
                             3.000 -                1.000  7700.000       NaN
              Renault Duster 0.000 -               34.000 13230.176  1622.405
              Renault Espace 1.000 -                1.000 27850.000       NaN
                                   Yes              1.000 27850.000       NaN
                             2.000 -                5.000 27100.000  4103.657
                             3.000 -                1.000 14900.000       NaN
Sedans        Audi A1        0.000 -              361.000 24141.792  3163.263
                                   Yes             65.000 23604.262  3738.103
                             1.000 -              324.000 18641.404  2635.318
                                   Yes            145.000 17822.214  2368.767
                             2.000 -              216.000 16726.495  2280.925
                                   Yes             51.000 16227.490  2140.542
                             3.000 -              276.000 14393.514  1892.550
                                   Yes            113.000 14646.142  1881.027
              Audi A3        0.000 -              543.000 24980.578  2491.416
                                   Yes            152.000 24455.250  1741.961
                             1.000 -              635.000 22679.172  5494.472
                                   Yes             78.000 21495.115  1289.066
                             2.000 -              467.000 20109.559  3941.787
                                   Yes             92.000 19205.467  1880.502
                             3.000 -              537.000 16834.685  3078.591
                                   Yes            117.000 16062.017  1687.635
              Opel Astra     0.000 -              200.000 19530.725  4264.587
                                   Yes            134.000 21449.179  4342.434
                             1.000 -              219.000 15374.991  1748.365
                                   Yes            101.000 16349.416  1717.429
                             2.000 -              186.000 13051.194  2190.287
                                   Yes             63.000 12667.206  1701.161
                             3.000 -              106.000 11508.849  2215.790
                                   Yes             44.000 12840.545  2265.052
              Opel Corsa     0.000 -              159.000 12649.805  2506.084
                                   Yes             33.000 14165.394  2677.391
                             1.000 -              250.000 10523.124  1883.611
                                   Yes             31.000 13167.355   958.357
                             2.000 -              181.000  8809.746  1336.718
                                   Yes             18.000 10923.889  1855.476
                             3.000 -              170.000  7912.924  1403.230
                                   Yes             33.000  8361.273  1639.520
              Opel Insignia  0.000 -              198.000 30582.217  6012.104
                                   Yes             53.000 31481.528  4903.352
                             1.000 -              182.000 20023.775  2614.047
                                   Yes             96.000 21022.281  1915.241
                             2.000 -              195.000 16008.036  3186.688
                                   Yes             50.000 18789.960  2498.948
                             3.000 -               98.000 12872.500  2107.240
                                   Yes             28.000 15295.964  1667.548
              Renault Clio   0.000 -              166.000 11462.657  2770.928
                                   Yes             24.000 13701.208  4721.698
                             1.000 -              287.000 15085.345  5462.872
                                   Yes             48.000 15564.312  4523.536
                             2.000 -              237.000 10011.000  2445.497
                                   Yes              5.000 13956.000  3471.913
                             3.000 -              203.000  9275.429  2752.388
                                   Yes             14.000 10240.714  2734.412
              Renault Espace 0.000 -                3.000 45478.667  3924.125
                             1.000 -               11.000 29019.182  3627.186
                                   Yes              2.000 29482.500   696.500
                             2.000 -                2.000 23800.000     0.000
                                   Yes              1.000 23990.000       NaN
                             3.000 -                2.000 22449.500  4879.744
Station wagon Audi A1        0.000 -                2.000 28944.500    77.075
                             1.000 -                6.000 18023.333  2482.327
                                   Yes              5.000 16676.000  1670.054
                             2.000 -                1.000 17440.000       NaN
                                   Yes              2.000 17700.000  4171.930
                             3.000 -                1.000 13999.000       NaN
                                   Yes              4.000 14447.750  1456.103
              Audi A3        0.000 -               85.000 24797.306  4651.885
                                   Yes             26.000 23915.538  1589.687
                             1.000 -               26.000 21163.962  3520.344
                                   Yes              6.000 21636.667  1167.128
                             2.000 -               62.000 18927.952  1435.566
                                   Yes             10.000 19525.000  1995.084
                             3.000 -               33.000 15931.788  1880.925
                                   Yes             34.000 15552.882  1895.290
              Opel Astra     0.000 -              190.000 22023.016  5250.990
                                   Yes            105.000 22646.962  4667.836
                             1.000 -              244.000 16067.266  2016.978
                                   Yes            123.000 17873.740  1139.447
                             2.000 -              193.000 13185.642  2099.986
                                   Yes             90.000 12731.522  1732.731
                             3.000 -              213.000 10835.277  2548.148
                                   Yes            127.000 11412.134  2429.625
              Opel Insignia  0.000 -              306.000 32544.542  5057.854
                                   Yes             92.000 33554.011  4974.443
                             1.000 -              274.000 21635.237  1720.691
                                   Yes            214.000 22414.664  1623.274
                             2.000 -              258.000 17162.628  2825.784
                                   Yes             81.000 17701.741  2185.729
                             3.000 -              308.000 13509.120  2170.287
                                   Yes            129.000 14075.659  2089.486
              Renault Clio   0.000 -               40.000 12635.400  3177.844
                                   Yes              3.000 14218.667  5599.656
                             1.000 -               95.000 11980.453  3006.262
                                   Yes              3.000 10156.667   568.624
                             2.000 -               74.000 11706.919  2837.835
                                   Yes             25.000 10051.360  1825.412
                             3.000 -               87.000  9264.678  2376.127
                                   Yes             10.000 10944.400  2983.491
              Renault Espace 0.000 -                9.000 45140.000  4059.021
                                   Yes              3.000 40983.333  2670.474
                             1.000 -                9.000 34838.889  4102.470
                                   Yes              5.000 33334.000  3612.047
                             2.000 -               10.000 26431.900  5349.191
                                   Yes              3.000 29096.667  5306.697
                             3.000 -               47.000 21370.532  2761.615
                                   Yes              5.000 24036.000  2962.420
Transporter   Opel Corsa     0.000 -                3.000  9933.333   493.288
                             2.000 -                1.000  7450.000       NaN
                             3.000 -                3.000  5433.333   175.594
              Renault Clio   0.000 -                2.000  9262.000     0.000
                                   Yes              1.000 10460.000       NaN
                             1.000 -                6.000 10058.500   761.313
                             2.000 -                9.000  8415.556   839.674
                             3.000 -               11.000  7376.364   876.838
              Renault Espace 0.000 -                1.000 32700.000       NaN
                             1.000 -                5.000 29297.800  1306.587
                             2.000 -                9.000 23861.000  3464.582
                             3.000 -               37.000 21124.297  3279.229
Van           Audi A1        0.000 -                1.000 29000.000       NaN
              Opel Corsa     3.000 -                2.000  7900.000     0.000
              Opel Insignia  1.000 -                1.000 20980.000       NaN
              Renault Clio   1.000 -                1.000  9900.000       NaN
                             2.000 -                1.000  9400.000       NaN
              Renault Espace 0.000 -              157.000 41615.159  8214.667
                                   Yes             91.000 36026.560  5703.426
                             1.000 -              184.000 31974.163  4888.102
                                   Yes             34.000 33262.618  3692.116
                             2.000 -              137.000 26507.088  3422.048
                                   Yes              2.000 27139.500   211.425
                             3.000 -              176.000 22182.267  3270.032
                                   Yes             30.000 21790.100  3690.171

                                                        min       25%  \
body_type     make_model     age   Inspection_new
Compact       Audi A1        0.000 -              16220.000 21435.000
                                   Yes            14900.000 20388.000
                             1.000 -              14500.000 16490.000
                                   Yes            13980.000 16445.000
                             2.000 -              10999.000 15450.000
                                   Yes            12490.000 15610.000
                             3.000 -              10900.000 13500.000
                                   Yes             9950.000 12922.500
              Audi A3        0.000 -              15500.000 22581.250
                                   Yes            24900.000 24900.000
                             1.000 -              14500.000 19999.000
                             2.000 -              13790.000 17525.000
                             3.000 -              12900.000 13500.000
                                   Yes            14900.000 15925.000
              Opel Astra     0.000 -              15816.000 16990.000
                                   Yes            16989.000 18481.500
                             1.000 -              11999.000 13990.000
                             2.000 -               9999.000 11955.000
                                   Yes            11980.000 11980.000
                             3.000 -               8450.000  9925.000
                                   Yes            10980.000 12987.500
              Opel Corsa     0.000 -                120.000 10990.000
                                   Yes             9245.000 10940.000
                             1.000 -               7499.000  9500.000
                                   Yes             8880.000 12790.000
                             2.000 -               6250.000  8500.000
                                   Yes             6950.000  8690.000
                             3.000 -               4990.000  7345.000
                                   Yes             6290.000  7305.000
              Opel Insignia  0.000 -              21900.000 34995.000
                             1.000 -              19900.000 20150.000
                             2.000 -              13490.000 15740.000
                             3.000 -              10350.000 10350.000
              Renault Clio   0.000 -               9545.000 10790.000
                                   Yes             9870.000 10860.000
                             1.000 -               8990.000 10412.500
                                   Yes             9899.000 15481.250
                             2.000 -               6950.000  8990.000
                                   Yes             8200.000  9490.000
                             3.000 -               5800.000  7850.000
                                   Yes             8399.000  8512.500
              Renault Espace 0.000 -              33500.000 36745.000
                             2.000 -              23990.000 23990.000
                             3.000 -              17900.000 18900.000
Convertible   Audi A3        1.000 -              10893.000 16446.500
                             2.000 -              20900.000 27350.000
                             3.000 -              20000.000 20000.000
Coupe         Audi A1        2.000 -              15900.000 15900.000
                             3.000 -              13950.000 13950.000
              Audi A3        2.000 -              19000.000 19000.000
                             3.000 -              16990.000 16990.000
              Opel Astra     0.000 -              29990.000 29990.000
                             3.000 Yes            14490.000 14490.000
              Opel Corsa     0.000 -               8800.000  9875.000
                             2.000 -               7500.000  7800.000
                                   Yes            10990.000 10990.000
                             3.000 -               6900.000  7200.000
              Opel Insignia  2.000 -              17094.000 17094.000
              Renault Clio   2.000 Yes            17990.000 17990.000
              Renault Espace 0.000 -              34140.000 34140.000

In [ ]:
df.drop("Inspection_new", axis=1, inplace=True)

### Paint_Type

In [ ]:
describe("Paint_Type")

Column Name    :  Paint_Type
----------------------------------------
Per_of_nulls   :  % 36.26
Num_of_nulls   :  5772
Num_of_uniques :  3
----------------------------------------
Metallic       9794
NaN            5772
Uni basic       347
Perl effect       6
Name: Paint_Type, dtype: int64

In [ ]:
df.Paint_Type.fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "Paint_Type"]).price.describe()

                              count      mean      std       min       25%  \
make_model     Paint_Type
Audi A1        -            808.000 18333.837 4453.516  8999.000 14923.250
               Metallic    1742.000 19061.978 4516.771  9950.000 15690.000
               Perl effect    1.000 28290.000      NaN 28290.000 28290.000
               Uni basic     63.000 20068.286 4092.876 12900.000 16900.000
Audi A2        Metallic       1.000 28200.000      NaN 28200.000 28200.000
Audi A3        -           1208.000 21019.580 5497.432  5555.000 17630.000
               Metallic    1792.000 20963.862 4753.167 10950.000 17990.000
               Uni basic     97.000 21318.206 3466.396 12900.000 18750.000
Opel Astra     -            785.000 15355.632 4675.494   255.000 11950.000
               Metallic    1713.000 16038.189 5080.444  6000.000 12500.000
               Perl effect    2.000 17745.000  346.482 17500.000 17622.500
               Uni basic     26.000 16741.654 3563.196  9700.000 14561.750
Opel Corsa     -            883.000 10118.905 2593.677    13.000  7900.000
               Metallic    1281.000 11710.792 3109.206   120.000  8900.000
               Perl effect    2.000 10145.000 1633.417  8990.000  9567.500
               Uni basic     53.000 10503.736 1779.998  6899.000  9495.000
Opel Insignia  -            795.000 21096.702 7544.992  8290.000 14980.000
               Metallic    1780.000 21559.661 7771.190  8913.000 15970.000
               Uni basic     23.000 26694.478 6806.895 12700.000 21225.000
Renault Clio   -            925.000 10883.814 3563.310  5445.000  8490.000
               Metallic     861.000 13178.424 4569.743  5700.000  9900.000
               Perl effect    1.000  8500.000      NaN  8500.000  8500.000
               Uni basic     52.000 10299.981 2349.085  7000.000  8375.000
Renault Duster -             17.000 13196.353 1686.115 10850.000 11900.000
               Metallic       1.000 12000.000      NaN 12000.000 12000.000
               Uni basic     16.000 13343.000 1625.593 10900.000 12162.500
Renault Espace -            351.000 29179.419 7349.073 12990.000 23495.000
               Metallic     623.000 30645.167 9465.900 12614.000 23950.000
               Uni basic     17.000 27975.000 4305.698 20995.000 24750.000

                                 50%       75%       max
make_model     Paint_Type
Audi A1        -           17600.000 21205.500 37900.000
               Metallic    17820.000 22278.500 32000.000
               Perl effect 28290.000 28290.000 28290.000
               Uni basic   19888.000 22110.000 29000.000
Audi A2        Metallic    28200.000 28200.000 28200.000
Audi A3        -           20900.000 23800.000 74600.000
               Metallic    20950.000 23335.000 67600.000
               Uni basic   21500.000 24300.000 26999.000
Opel Astra     -           14950.000 17690.000 39433.000
               Metallic    15450.000 17992.000 37995.000
               Perl effect 17745.000 17867.500 17990.000
               Uni basic   16482.000 18250.000 24790.000
Opel Corsa     -            9940.000 11194.500 18490.000
               Metallic    11280.000 14213.000 18622.000
               Perl effect 10145.000 10722.500 11300.000
               Uni basic    9849.000 11294.000 15390.000
Opel Insignia  -           19900.000 25512.500 42475.000
               Metallic    19999.000 23950.000 52120.000
               Uni basic   27900.000 31482.500 37599.000
Renault Clio   -            9999.000 11380.000 31500.000
               Metallic    11400.000 15780.000 29850.000
               Perl effect  8500.000  8500.000  8500.000
               Uni basic    9985.000 11017.500 18950.000
Renault Duster -           13189.000 14399.000 16033.000
               Metallic    12000.000 12000.000 12000.000
               Uni basic   13219.500 14505.000 16033.000
Renault Espace -           28990.000 33400.000 54205.000
               Metallic    28890.000 35989.500 68320.000
               Uni basic   28250.000 31900.000 34000.000

In [ ]:
df.Paint_Type.replace("-", np.nan, inplace=True)

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        df.loc[cond2, "Paint_Type"] = df.loc[cond2, "Paint_Type"].fillna(method="ffill").fillna(method="bfill")
                
for group1 in list(df["make_model"].unique()):
    cond1 = df["make_model"]==group1
    df.loc[cond1, "Paint_Type"] = df.loc[cond1, "Paint_Type"].fillna(method="ffill").fillna(method="bfill")            
           
df["Paint_Type"] = df["Paint_Type"].fillna(method="ffill").fillna(method="bfill")

In [ ]:
df.Paint_Type.value_counts(dropna=False)

Metallic       15250
Uni basic        637
Perl effect       32
Name: Paint_Type, dtype: int64

### Upholstery_type

In [ ]:
describe("Upholstery_type")

Column Name    :  Upholstery_type
----------------------------------------
Per_of_nulls   :  % 30.6
Num_of_nulls   :  4871
Num_of_uniques :  5
----------------------------------------
Cloth           8423
NaN             4871
Part leather    1499
Full leather    1009
Velour            60
alcantara         57
Name: Upholstery_type, dtype: int64

In [ ]:
df.Upholstery_type.replace(["Cloth", "Part leather","Full leather","Velour","alcantara"], 
                           ["Cloth","Leather","Leather","Cloth","Cloth"], 
                           inplace=True)

In [ ]:
df.Upholstery_type.value_counts(dropna=False)

Cloth      8540
NaN        4871
Leather    2508
Name: Upholstery_type, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        df.loc[cond2, "Upholstery_type"] = df.loc[cond2, "Upholstery_type"].fillna(method="ffill").fillna(method="bfill")
                
for group1 in list(df["make_model"].unique()):
    cond1 = df["make_model"]==group1
    df.loc[cond1, "Upholstery_type"] = df.loc[cond1, "Upholstery_type"].fillna(method="ffill").fillna(method="bfill")            
           
df["Upholstery_type"] = df["Upholstery_type"].fillna(method="ffill").fillna(method="bfill")

In [ ]:
df.Upholstery_type.value_counts(dropna=False)

Cloth      12333
Leather     3586
Name: Upholstery_type, dtype: int64

### Nr_of_Doors

In [ ]:
describe("Nr_of_Doors")

Column Name    :  Nr_of_Doors
----------------------------------------
Per_of_nulls   :  % 1.33
Num_of_nulls   :  212
Num_of_uniques :  6
----------------------------------------
5.000    11575
4.000     3079
3.000      832
2.000      219
NaN        212
1.000        1
7.000        1
Name: Nr_of_Doors, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Nr_of_Doors"].mode())
            if mode != []:
                df.loc[cond, "Nr_of_Doors"] = df.loc[cond, "Nr_of_Doors"].fillna(df[cond]["Nr_of_Doors"].mode()[0])
            else:
                df.loc[cond, "Nr_of_Doors"] = df.loc[cond, "Nr_of_Doors"].fillna(df["Nr_of_Doors"].mode()[0])

In [ ]:
df.Nr_of_Doors.value_counts(dropna=False)

5.000    11787
4.000     3079
3.000      832
2.000      219
1.000        1
7.000        1
Name: Nr_of_Doors, dtype: int64

### Nr_of_Seats

In [ ]:
describe("Nr_of_Seats")

Column Name    :  Nr_of_Seats
----------------------------------------
Per_of_nulls   :  % 6.14
Num_of_nulls   :  977
Num_of_uniques :  6
----------------------------------------
5.000    13336
4.000     1125
NaN        977
7.000      362
2.000      116
6.000        2
3.000        1
Name: Nr_of_Seats, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Nr_of_Seats"].mode())
            if mode != []:
                df.loc[cond, "Nr_of_Seats"] = df.loc[cond, "Nr_of_Seats"].fillna(df[cond]["Nr_of_Seats"].mode()[0])
            else:
                df.loc[cond, "Nr_of_Seats"] = df.loc[cond, "Nr_of_Seats"].fillna(df["Nr_of_Seats"].mode()[0])

In [ ]:
df.Nr_of_Seats.value_counts(dropna=False)

5.000    14308
4.000     1127
7.000      362
2.000      119
6.000        2
3.000        1
Name: Nr_of_Seats, dtype: int64

### Displacement_cc

In [ ]:
describe("Displacement_cc")

Column Name    :  Displacement_cc
----------------------------------------
Per_of_nulls   :  % 3.12
Num_of_nulls   :  496
Num_of_uniques :  77
----------------------------------------
1598.000     4761
999.000      2438
1398.000     1314
1399.000      749
1229.000      677
1956.000      670
1461.000      595
1490.000      559
NaN           496
1422.000      467
1197.000      353
898.000       351
1395.000      320
1968.000      301
1149.000      288
1618.000      212
1798.000      210
1498.000      196
1600.000      130
1248.000      110
1997.000      103
1364.000      102
1400.000       90
998.000        72
1500.000       50
2000.000       46
1000.000       40
1.000          36
1998.000       25
2480.000       20
1200.000       18
1984.000       18
1397.000       11
899.000        11
160.000         6
929.000         5
1499.000        5
997.000         4
1596.000        4
139.000         4
900.000         4
1599.000        3
1199.000        3
1396.000        3
1495.000        2
1589.000        2
1300.000        2
2.000           2
995.000         2
1496.000        1
890.000         1
1580.000        1
1995.000        1
1333.000        1
54.000          1
1533.000        1
1100.000        1
1350.000        1
16000.000       1
1856.000        1
1568.000        1
1896.000        1
1584.000        1
996.000         1
1696.000        1
1686.000        1
15898.000       1
1368.000        1
140.000         1
973.000         1
1239.000        1
1369.000        1
1390.000        1
122.000         1
1198.000        1
1195.000        1
2967.000        1
1800.000        1
Name: Displacement_cc, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Displacement_cc"].mode())
            if mode != []:
                df.loc[cond, "Displacement_cc"] = df.loc[cond, "Displacement_cc"].fillna(df[cond]["Displacement_cc"].mode()[0])
            else:
                df.loc[cond, "Displacement_cc"] = df.loc[cond, "Displacement_cc"].fillna(df["Displacement_cc"].mode()[0])

In [ ]:
df.Displacement_cc.value_counts(dropna=False)

1598.000     5044
999.000      2467
1398.000     1387
1399.000      768
1229.000      678
1956.000      670
1461.000      667
1490.000      559
1422.000      467
1197.000      372
898.000       351
1395.000      320
1968.000      301
1149.000      288
1618.000      212
1798.000      210
1498.000      196
1600.000      130
1248.000      110
1997.000      103
1364.000      102
1400.000       90
998.000        72
1500.000       50
2000.000       46
1000.000       40
1.000          36
1998.000       25
2480.000       20
1200.000       18
1984.000       18
1397.000       11
899.000        11
160.000         6
929.000         5
1499.000        5
997.000         4
1596.000        4
139.000         4
900.000         4
1599.000        3
1199.000        3
1396.000        3
1495.000        2
1589.000        2
1300.000        2
2.000           2
995.000         2
1496.000        1
890.000         1
1580.000        1
1995.000        1
1333.000        1
54.000          1
1533.000        1
1100.000        1
1350.000        1
16000.000       1
1856.000        1
1568.000        1
1896.000        1
1584.000        1
996.000         1
1696.000        1
1686.000        1
15898.000       1
1368.000        1
140.000         1
973.000         1
1239.000        1
1369.000        1
1390.000        1
122.000         1
1198.000        1
1195.000        1
2967.000        1
1800.000        1
Name: Displacement_cc, dtype: int64

### Weight_kg

In [ ]:
describe("Weight_kg")

Column Name    :  Weight_kg
----------------------------------------
Per_of_nulls   :  % 43.81
Num_of_nulls   :  6974
Num_of_uniques :  434
----------------------------------------
NaN         6974
1163.000     574
1360.000     356
1165.000     301
1335.000     242
1135.000     213
1199.000     205
1734.000     170
1180.000     168
1503.000     165
1350.000     155
1355.000     135
1260.000     127
1275.000     112
1278.000     110
1487.000     109
1425.000     109
1255.000     108
1200.000     107
1522.000     103
1273.000     103
1280.000     102
1403.000      91
1120.000      90
1659.000      89
1195.000      89
1701.000      87
1250.000      84
1441.000      82
1308.000      80
1285.000      80
1613.000      75
1110.000      75
1279.000      72
1364.000      70
1345.000      67
1733.000      65
1325.000      64
1141.000      64
1685.000      64
1071.000      64
1230.000      63
1845.000      56
1090.000      54
1052.000      53
1154.000      52
1664.000      52
1513.000      51
1065.000      50
1237.000      49
1119.000      46
1088.000      46
1205.000      46
1440.000      46
1265.000      45
1395.000      44
1585.000      43
1666.000      43
1209.000      43
1162.000      42
1365.000      42
1134.000      42
1248.000      40
1393.000      40
1288.000      40
1087.000      39
1472.000      38
1092.000      38
1263.000      36
1552.000      36
1415.000      35
1820.000      35
1456.000      35
1146.000      33
1615.000      33
1623.000      32
1840.000      32
1328.000      31
1228.000      31
1680.000      31
1322.000      29
1215.000      29
1633.000      29
1385.000      28
1743.000      27
1276.000      27
1315.000      27
1063.000      27
1155.000      27
1571.000      27
1059.000      26
1220.000      25
1580.000      25
1660.000      24
1105.000      22
1790.000      22
1173.000      21
1695.000      21
1635.000      20
1300.000      20
1388.000      20
1170.000      20
1225.000      19
1582.000      19
1198.000      19
1890.000      19
1370.000      19
1537.000      18
1310.000      18
1655.000      17
1400.000      16
1518.000      16
1843.000      16
1540.000      16
1235.000      15
1380.000      15
2353.000      15
1760.000      15
1055.000      15
1305.000      14
1510.000      14
1708.000      14
1596.000      14
1640.000      14
1270.000      13
1815.000      13
1630.000      13
1758.000      13
1079.000      13
1214.000      12
1100.000      12
1240.000      12
1340.000      12
2300.000      12
1378.000      12
980.000       11
1140.000      11
1234.000      11
1684.000      11
1175.000      11
1647.000      11
1035.000      11
1717.000      11
1082.000      10
1567.000      10
1485.000      10
1295.000      10
1203.000      10
1156.000      10
1244.000       9
1500.000       9
1624.000       9
1233.000       9
1609.000       9
1658.000       9
1833.000       9
1330.000       9
1144.000       9
1410.000       9
1290.000       9
1320.000       9
1133.000       9
1178.000       8
1115.000       8
1880.000       8
1259.000       8
1740.000       8
1179.000       8
1437.000       8
1245.000       8
1216.000       8
1625.000       8
1372.000       8
1772.000       8
1239.000       8
1341.000       8
1674.000       8
1550.000       8
1125.000       7
1560.000       7
1204.000       7
1164.000       7
1543.000       7
1584.000       7
1901.000       7
1665.000       7
1975.000       7
1525.000       7
1985.000       7
1256.000       7
1157.000       6
1293.000       6
1765.000       6
1126.000       6
1124.000       6
1651.000       6
2000.000       6
1227.000       6
1940.000       6
1184.000       6
1091.000       6
1697.000       5
1621.000       5
1795.000       5
1735.000       5
1626.000       5
1390.000       5
1356.000       5
1634.000       5
1716.000       5
1145.000       5
1326.000       5
2471.000       5
1610.000       5
1247.000       4
1084.000       4
1452.000       4
1224.000       4
1160.000       4
1670.000       4
1099.000       4
1123.000       4
1121.000       4
1352.000       4
1194.000       4
1538.000       4
1153.000       4
1196.000       4
1054.000       4
1778.000       4
1736.000       4
1097.000       4
1865.000       4
1600.000       4
1459.000       4
1422.000       4
1462.000       4
1130.000       4
1900.000       4
1622.000       4
1447.000       4
2410.000       4
1455.000       4
1530.000       4
1800.000       4
1166.000       4
1618.000       4
1236.000       4
1564.000       4
1875.000       3
1490.000       3
1114.000       3
1809.000       3
1185.000       3
1750.000       3
1958.000       3
1190.000       3
1786.000       3
1730.000       3
1673.000       3
1086.000       3
1142.000       3
1495.000       3
1118.000       3
1475.000       3
1590.000       3
1238.000       3
1608.000       3
1284.000       3
1449.000       3
1139.000       3
1566.000       3
1289.000       3
1850.000       3
1549.000       3
1405.000       3
1136.000       3
1041.000       3
1066.000       3
1010.000       3
1779.000       3
1152.000       2
1929.000       2
2450.000       2
1483.000       2
1128.000       2
1838.000       2
1534.000       2
1788.000       2
2280.000       2
2400.000       2
1807.000       2
1563.000       2
1387.000       2
1741.000       2
1094.000       2
1515.000       2
1465.000       2
1138.000       2
1595.000       2
1182.000       2
1375.000       2
2320.000       2
1413.000       2
1354.000       2
1127.000       2
1408.000       2
1176.000       2
1318.000       2
1470.000       2
1147.000       2
1298.000       2
1268.000       2
1675.000       2
1211.000       2
977.000        2
1.000          2
1040.000       2
1210.000       2
1060.000       2
1208.000       2
1536.000       2
1891.000       1
1939.000       1
1797.000       1
1847.000       1
1780.000       1
1724.000       1
1277.000       1
1702.000       1
1791.000       1
1761.000       1
1804.000       1
1058.000       1
1009.000       1
1057.000       1
1030.000       1
1711.000       1
1201.000       1
1143.000       1
1017.000       1
900.000        1
1686.000       1
1267.000       1
1189.000       1
1161.000       1
1819.000       1
2044.000       1
1648.000       1
1523.000       1
1683.000       1
1272.000       1
1885.000       1
1505.000       1
1332.000       1
1281.000       1
1785.000       1
1379.000       1
1319.000       1
1430.000       1
1257.000       1
1950.000       1
1333.000       1
1397.000       1
1363.000       1
1471.000       1
1291.000       1
1254.000       1
1476.000       1
1366.000       1
1575.000       1
1555.000       1
1374.000       1
1870.000       1
1720.000       1
1217.000       1
1792.000       1
1223.000       1
1705.000       1
1650.000       1
1565.000       1
102.000        1
1207.000       1
1169.000       1
1171.000       1
1645.000       1
1181.000       1
1206.000       1
1150.000       1
1420.000       1
1905.000       1
1435.000       1
1188.000       1
1591.000       1
2270.000       1
1548.000       1
2295.000       1
1668.000       1
1428.000       1
2110.000       1
2275.000       1
1713.000       1
1589.000       1
2240.000       1
1396.000       1
2355.000       1
1492.000       1
1598.000       1
2080.000       1
1649.000       1
1764.000       1
2115.000       1
1507.000       1
1974.000       1
1601.000       1
1252.000       1
1132.000       1
1312.000       1
1444.000       1
1394.000       1
1382.000       1
1383.000       1
1343.000       1
1294.000       1
1302.000       1
1283.000       1
1159.000       1
840.000        1
1137.000       1
1213.000       1
1960.000       1
1258.000       1
1167.000       1
1331.000       1
2037.000       1
Name: Weight_kg, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Weight_kg"].mode())
            if mode != []:
                df.loc[cond, "Weight_kg"] = df.loc[cond, "Weight_kg"].fillna(df[cond]["Weight_kg"].mode()[0])
            else:
                df.loc[cond, "Weight_kg"] = df.loc[cond, "Weight_kg"].fillna(df["Weight_kg"].mode()[0])

In [ ]:
df.Displacement_cc.value_counts(dropna=False)

1598.000     5044
999.000      2467
1398.000     1387
1399.000      768
1229.000      678
1956.000      670
1461.000      667
1490.000      559
1422.000      467
1197.000      372
898.000       351
1395.000      320
1968.000      301
1149.000      288
1618.000      212
1798.000      210
1498.000      196
1600.000      130
1248.000      110
1997.000      103
1364.000      102
1400.000       90
998.000        72
1500.000       50
2000.000       46
1000.000       40
1.000          36
1998.000       25
2480.000       20
1200.000       18
1984.000       18
1397.000       11
899.000        11
160.000         6
929.000         5
1499.000        5
997.000         4
1596.000        4
139.000         4
900.000         4
1599.000        3
1199.000        3
1396.000        3
1495.000        2
1589.000        2
1300.000        2
2.000           2
995.000         2
1496.000        1
890.000         1
1580.000        1
1995.000        1
1333.000        1
54.000          1
1533.000        1
1100.000        1
1350.000        1
16000.000       1
1856.000        1
1568.000        1
1896.000        1
1584.000        1
996.000         1
1696.000        1
1686.000        1
15898.000       1
1368.000        1
140.000         1
973.000         1
1239.000        1
1369.000        1
1390.000        1
122.000         1
1198.000        1
1195.000        1
2967.000        1
1800.000        1
Name: Displacement_cc, dtype: int64

### Drive_chain

In [ ]:
describe("Drive_chain")

Column Name    :  Drive_chain
----------------------------------------
Per_of_nulls   :  % 43.08
Num_of_nulls   :  6858
Num_of_uniques :  3
----------------------------------------
front    8886
NaN      6858
4WD       171
rear        4
Name: Drive_chain, dtype: int64

In [ ]:
df.Drive_chain.fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model","body_type","Drive_chain"]).price.describe()

                                            count      mean       std  \
make_model     body_type     Drive_chain
Audi A1        Compact       -            352.000 17620.869  4226.116
                             4WD            2.000 14790.000  1258.650
                             front        685.000 20008.223  4511.348
               Coupe         -              2.000 14925.000  1378.858
               Sedans        -            561.000 17830.440  4362.321
                             4WD            1.000 15450.000       NaN
                             front        989.000 19133.794  4441.969
               Station wagon -              3.000 24593.000  7537.216
                             front         18.000 16681.111  2493.673
               Van           front          1.000 29000.000       NaN
Audi A2        Off-Road      front          1.000 28200.000       NaN
Audi A3        Compact       -             25.000 18236.520  3427.236
                             4WD            1.000 67600.000       NaN
                             front        156.000 18839.365  6078.743
               Convertible   -              4.000 26112.500  6123.775
                             4WD            1.000 56100.000       NaN
                             front          3.000 20897.667 10003.500
               Coupe         -              1.000 16990.000       NaN
                             front          3.000 17996.667  1005.004
               Sedans        -            891.000 20787.714  5846.561
                             4WD           17.000 32913.765 20353.178
                             front       1713.000 21223.413  3546.978
               Station wagon -            149.000 20254.745  5473.077
                             front        133.000 21165.647  3552.001
Opel Astra     Compact       -             81.000 17993.346  6740.198
                             front        104.000 14802.837  5080.910
               Coupe         -              2.000 22240.000 10960.155
               Off-Road      front          1.000 18590.000       NaN
               Sedans        -            507.000 15488.444  4123.966
                             4WD            2.000 13075.000  3641.600
                             front        544.000 16416.243  4600.632
               Station wagon -            588.000 14923.395  4925.886
                             front        697.000 16290.032  5318.146
Opel Corsa     Compact       -            678.000 10877.917  2906.949
                             front        641.000 12481.011  3015.968
               Coupe         -              6.000  9198.333  1848.463
                             front          7.000  8407.143  1342.395
               Off-Road      -              3.000  8166.667   461.880
               Sedans        -            359.000  9755.081  2483.224
                             front        516.000 10519.351  2692.189
               Transporter   -              1.000 10500.000       NaN
                             front          6.000  7175.000  2073.343
               Van           -              2.000  7900.000     0.000
Opel Insignia  Compact       -             17.000 28728.353 10844.301
                             front         10.000 28355.000 12606.283
               Coupe         -              1.000 17094.000       NaN
               Off-Road      -              1.000 33490.000       NaN
                             4WD            5.000 28232.800  8948.569
                             front          1.000 31505.000       NaN
               Sedans        -            368.000 19794.959  6394.251
                             4WD           26.000 34139.346  6543.818
                             front        505.000 21675.178  7462.771
                             rear           1.000 18990.000       NaN
               Station wagon -            705.000 19525.681  6954.362
                             4WD           63.000 27784.540 10677.083
                             front        892.000 22489.775  7656.689
                             rear           2.000 15925.000  4277.996
               Van           front          1.000 20980.000       NaN
Renault Clio   Compact       -            270.000 12889.822  3883.297
                             4WD            1.000  9680.000       NaN
                             front        213.000 12359.113  4342.140
               Coupe         front          1.000 17990.000       NaN
               Off-Road      -              1.000  7700.000       NaN
                             front          1.000 17990.000       NaN
               Sedans        -            558.000 12059.611  4820.903
                             4WD            9.000 23021.000     0.000
                             front        416.000 11610.428  3872.653
                             rear           1.000 10490.000       NaN
               Station wagon -            181.000 11223.812  3357.188
                             4WD            1.000 15798.000       NaN
                             front        155.000 10983.510  2589.221
               Transporter   -             21.000  8468.857  1360.590
                             front          8.000  8546.125  1346.641
               Van           -              1.000  9900.000       NaN
                             front          1.000  9400.000       NaN
Renault Duster Off-Road      -             32.000 13343.000  1599.159
                             4WD            2.000 11425.000   813.173
Renault Espace Compact       -              5.000 31676.000 10601.124
                             front          1.000 21900.000       NaN
               Coupe         -              2.000 30567.000  5052.985
               Off-Road      -              5.000 28600.000  2920.402
                             front          3.000 21033.333  5547.372
               Sedans        -             16.000 30763.188  8388.425
                             front          5.000 27778.000  3676.740
               Station wagon -             20.000 28593.950  7401.774
                             4WD            1.000 35990.000       NaN
                             front         70.000 26825.214  9096.536
               Transporter   -             45.000 22355.289  3910.120
                             4WD            1.000 30000.000       NaN
                             front          6.000 23258.167  5973.317
               Van           -            394.000 29624.208  8543.180
                             4WD           38.000 38150.763 10013.779
                             front        379.000 31525.164  8343.192

                                               min       25%       50%  \
make_model     body_type     Drive_chain
Audi A1        Compact       -           10490.000 14990.000 15900.000
                             4WD         13900.000 14345.000 14790.000
                             front        9950.000 16430.000 19890.000
               Coupe         -           13950.000 14437.500 14925.000
               Sedans        -            8999.000 14900.000 16490.000
                             4WD         15450.000 15450.000 15450.000
                             front       10000.000 15838.000 18500.000
               Station wagon -           15890.000 22390.000 28890.000
                             front       12950.000 15000.000 16356.000
               Van           front       29000.000 29000.000 29000.000
Audi A2        Off-Road      front       28200.000 28200.000 28200.000
Audi A3        Compact       -           12900.000 16400.000 17894.000
                             4WD         67600.000 67600.000 67600.000
                             front       13100.000 13910.000 17724.500
               Convertible   -           20000.000 21500.000 25750.000
                             4WD         56100.000 56100.000 56100.000
                             front       10893.000 15896.500 20900.000
               Coupe         -           16990.000 16990.000 16990.000
                             front       16990.000 17495.000 18000.000
               Sedans        -           10550.000 17000.000 19900.000
                             4WD         13780.000 16999.000 22499.000
                             front       10990.000 18700.000 21490.000
               Station wagon -            5555.000 16999.000 19800.000
                             front       13250.000 18480.000 21450.000
Opel Astra     Compact       -            9490.000 14900.000 15400.000
                             front        8450.000 11955.000 12955.000
               Coupe         -           14490.000 18365.000 22240.000
               Off-Road      front       18590.000 18590.000 18590.000
               Sedans        -            6500.000 12962.000 15249.000
                             4WD         10500.000 11787.500 13075.000
                             front        8860.000 12900.000 15890.000
               Station wagon -             255.000 10900.000 14895.000
                             front        6690.000 12250.000 15890.000
Opel Corsa     Compact       -             120.000  8750.000  9950.000
                             front        4990.000 10250.000 12940.000
               Coupe         -            7200.000  7600.000  9200.000
                             front        6900.000  7500.000  8500.000
               Off-Road      -            7900.000  7900.000  7900.000
               Sedans        -              13.000  7879.000  9280.000
                             front        5970.000  8500.000  9900.000
               Transporter   -           10500.000 10500.000 10500.000
                             front        5250.000  5487.500  6525.000
               Van           -            7900.000  7900.000  7900.000
Opel Insignia  Compact       -           13490.000 19900.000 26990.000
                             front       10350.000 16500.000 35845.000
               Coupe         -           17094.000 17094.000 17094.000
               Off-Road      -           33490.000 33490.000 33490.000
                             4WD         12750.000 28500.000 32345.000
                             front       31505.000 31505.000 31505.000
               Sedans        -            8600.000 15475.000 18895.000
                             4WD         17480.000 32325.500 34991.000
                             front        9650.000 16690.000 20400.000
                             rear        18990.000 18990.000 18990.000
               Station wagon -            8290.000 14480.000 18880.000
                             4WD         11480.000 16940.000 34550.000
                             front        8990.000 16182.000 21385.000
                             rear        12900.000 14412.500 15925.000
               Van           front       20980.000 20980.000 20980.000
Renault Clio   Compact       -            5800.000 10589.000 11380.000
                             4WD          9680.000  9680.000  9680.000
                             front        6900.000  8750.000 11190.000
               Coupe         front       17990.000 17990.000 17990.000
               Off-Road      -            7700.000  7700.000  7700.000
                             front       17990.000 17990.000 17990.000
               Sedans        -            5700.000  8660.000  9999.000
                             4WD         23021.000 23021.000 23021.000
                             front        5445.000  9480.000 10690.000
                             rear        10490.000 10490.000 10490.000
               Station wagon -            6000.000  8490.000  9990.000
                             4WD         15798.000 15798.000 15798.000
                             front        5900.000  9615.000 10450.000
               Transporter   -            5900.000  7790.000  8490.000
                             front        6900.000  7600.000  8531.000
               Van           -            9900.000  9900.000  9900.000
                             front        9400.000  9400.000  9400.000
Renault Duster Off-Road      -           10900.000 12162.500 13219.500
                             4WD         10850.000 11137.500 11425.000
Renault Espace Compact       -           17900.000 23990.000 33500.000
                             front       21900.000 21900.000 21900.000
               Coupe         -           26994.000 28780.500 30567.000
               Off-Road      -           24900.000 27850.000 27850.000
                             front       14900.000 18700.000 22500.000
               Sedans        -           18999.000 25797.500 27625.500
                             front       23800.000 23800.000 29490.000
               Station wagon -           16900.000 24872.500 27250.000
                             4WD         35990.000 35990.000 35990.000
                             front       17900.000 20455.000 21950.000
               Transporter   -           14999.000 19900.000 21000.000
                             4WD         30000.000 30000.000 30000.000
                             front       17000.000 19262.500 21500.000
               Van           -           12990.000 23990.000 27545.000
                             4WD         24950.000 31900.000 34200.000
                             front       12614.000 25050.000 31360.000

                                               75%       max
make_model     body_type     Drive_chain
Audi A1        Compact       -           20885.750 29190.000
                             4WD         15235.000 15680.000
                             front       22690.000 31990.000
               Coupe         -           15412.500 15900.000
               Sedans        -           20700.000 37900.000
                             4WD         15450.000 15450.000
                             front       21999.000 32000.000
               Station wagon -           28944.500 28999.000
                             front       17300.000 21450.000
               Van           front       29000.000 29000.000
Audi A2        Off-Road      front       28200.000 28200.000
Audi A3        Compact       -           18700.000 29950.000
                             4WD         67600.000 67600.000
                             front       20810.000 41495.000
               Convertible   -           30362.500 32950.000
                             4WD         56100.000 56100.000
                             front       25900.000 30900.000
               Coupe         -           16990.000 16990.000
                             front       18500.000 19000.000
               Sedans        -           22990.000 64900.000
                             4WD         51999.000 74600.000
                             front       23800.000 34738.000
               Station wagon -           23401.000 63900.000
                             front       24200.000 27400.000
Opel Astra     Compact       -           17800.000 37995.000
                             front       16344.000 39433.000
               Coupe         -           26115.000 29990.000
               Off-Road      front       18590.000 18590.000
               Sedans        -           16990.000 30750.000
                             4WD         14362.500 15650.000
                             front       18457.500 32950.000
               Station wagon -           17714.000 33995.000
                             front       18490.000 34900.000
Opel Corsa     Compact       -           12990.000 18501.000
                             front       14790.000 18622.000
               Coupe         -           10867.500 11100.000
                             front        8750.000 10950.000
               Off-Road      -            8300.000  8700.000
               Sedans        -           11265.500 18490.000
                             front       11692.500 18490.000
               Transporter   -           10500.000 10500.000
                             front        9062.500  9700.000
               Van           -            7900.000  7900.000
Opel Insignia  Compact       -           37899.000 49884.000
                             front       38365.000 39990.000
               Coupe         -           17094.000 17094.000
               Off-Road      -           33490.000 33490.000
                             4WD         32793.000 34776.000
                             front       31505.000 31505.000
               Sedans        -           21457.500 40990.000
                             4WD         37356.250 48950.000
                             front       25464.000 49350.000
                             rear        18990.000 18990.000
               Station wagon -           22450.000 44970.000
                             4WD         36970.000 42475.000
                             front       27174.750 52120.000
                             rear        17437.500 18950.000
               Van           front       20980.000 20980.000
Renault Clio   Compact       -           14950.000 28949.000
                             4WD          9680.000  9680.000
                             front       15485.000 29740.000
               Coupe         front       17990.000 17990.000
               Off-Road      -            7700.000  7700.000
                             front       17990.000 17990.000
               Sedans        -           14495.000 31500.000
                             4WD         23021.000 23021.000
                             front       12960.000 29850.000
                             rear        10490.000 10490.000
               Station wagon -           13990.000 20800.000
                             4WD         15798.000 15798.000
                             front       11500.000 20680.000
               Transporter   -            9290.000 10798.000
                             front        9417.750 10460.000
               Van           -            9900.000  9900.000
                             front        9400.000  9400.000
Renault Duster Off-Road      -           14505.000 16033.000
                             4WD         11712.500 12000.000
Renault Espace Compact       -           39990.000 43000.000
                             front       21900.000 21900.000
               Coupe         -           32353.500 34140.000
               Off-Road      -           29500.000 32900.000
                             front       24100.000 25700.000
               Sedans        -           33825.000 48498.000
                             front       30900.000 30900.000
               Station wagon -           31842.500 45490.000
                             4WD         35990.000 35990.000
                             front       30732.500 52990.000
               Transporter   -           24900.000 31000.000
                             4WD         30000.000 30000.000
                             front       26624.250 32700.000
               Van           -           34368.750 63477.000
                             4WD         45747.000 57990.000
                             front       36151.000 68320.000

In [ ]:
df.Drive_chain.replace("-", np.nan, inplace=True)

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Drive_chain"].mode())
            if mode != []:
                df.loc[cond, "Drive_chain"] = df.loc[cond, "Drive_chain"].fillna(df[cond]["Drive_chain"].mode()[0])
            else:
                df.loc[cond, "Drive_chain"] = df.loc[cond, "Drive_chain"].fillna(df["Drive_chain"].mode()[0])

In [ ]:
df.Drive_chain.value_counts(dropna=True)

front    15711
4WD        204
rear         4
Name: Drive_chain, dtype: int64

### Consumption_comb

In [ ]:
describe("Consumption_comb")

Column Name    :  Consumption_comb
----------------------------------------
Per_of_nulls   :  % 12.77
Num_of_nulls   :  2033
Num_of_uniques :  72
----------------------------------------
NaN       2033
5.400      770
3.900      733
4.000      713
5.100      657
4.400      623
5.600      618
4.700      602
3.800      585
4.800      546
5.000      545
4.500      523
5.200      454
4.200      435
4.600      426
4.900      393
5.500      380
5.300      380
3.700      369
5.900      369
4.100      342
5.700      342
6.000      331
4.300      307
3.300      307
3.500      288
6.200      216
3.600      194
6.300      181
6.100      175
5.800      164
6.600      148
6.800      136
3.400      106
6.400       75
3.000       69
7.400       66
6.500       43
6.700       43
7.100       38
10.000      34
6.900       27
3.200       25
8.300       20
7.600       14
7.000       10
3.100        7
7.200        6
7.800        6
8.000        5
51.000       4
8.600        4
7.900        3
8.700        3
1.600        3
7.300        2
8.100        2
40.000       2
38.000       2
0.000        2
9.100        1
43.000       1
7.500        1
13.800       1
55.000       1
54.000       1
1.200        1
32.000       1
33.000       1
50.000       1
1.000        1
46.000       1
11.000       1
Name: Consumption_comb, dtype: int64

In [ ]:
df.Consumption_comb.fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model","body_type","Consumption_comb"]).price.describe()

                                                count      mean       std  \
make_model     body_type     Consumption_comb
Audi A1        Compact       3.0                4.000 14370.250  4481.393
                             3.4                6.000 12755.000   900.750
                             3.5                3.000 14613.000  1848.098
                             3.6                5.000 13960.000  1232.071
                             3.7               50.000 15902.200  2960.324
                             3.8               18.000 16158.056  2265.763
                             3.9               41.000 15771.902  1567.307
                             4.0               79.000 16795.671  2620.874
                             4.1               38.000 16540.737  1754.464
                             4.2               87.000 15631.126  2420.347
                             4.3               17.000 16628.706  2467.669
                             4.4              193.000 17618.922  3250.845
                             4.5               11.000 21482.909  1918.658
                             4.6               52.000 20729.962  2195.464
                             4.7               33.000 22102.667  1889.931
                             4.8               93.000 25162.548  3080.468
                             4.9              176.000 23133.290  3723.040
                             5.0                9.000 21739.444  2364.487
                             5.1               50.000 18187.280  4445.452
                             5.2               18.000 19429.833  3737.664
                             5.6                2.000 19888.000     0.000
                             5.8                2.000 22495.000   841.457
                             6.0                8.000 28797.125   355.356
                             13.8               1.000 12990.000       NaN
                             -                 43.000 16765.791  4426.026
               Coupe         4.2                1.000 13950.000       NaN
                             -                  1.000 15900.000       NaN
               Sedans        3.0                1.000 15450.000       NaN
                             3.4               20.000 14829.400  1517.956
                             3.5               48.000 15679.125  1535.780
                             3.6               13.000 15590.000  2503.514
                             3.7              140.000 15242.100  2130.600
                             3.8               95.000 16135.463  2095.939
                             3.9               93.000 16511.710  1919.916
                             4.0               81.000 19200.000  2282.083
                             4.1               15.000 16189.333  2096.758
                             4.2              220.000 14813.968  1838.279
                             4.3               43.000 16173.558  1713.437
                             4.4              156.000 17887.404  2900.445
                             4.5                8.000 19561.000  1725.197
                             4.6               61.000 20956.197  1483.175
                             4.7                9.000 20541.333  2427.125
                             4.8              257.000 25246.179  2742.582
                             4.9               84.000 21241.690  3559.583
                             5.0                7.000 23258.571  5778.473
                             5.1               27.000 16992.074  2964.090
                             5.2                5.000 20150.200  2021.626
                             5.3                5.000 20304.600  1130.643
                             5.6               11.000 21114.364  2467.252
                             5.8                2.000 20490.000  4242.641
                             5.9                1.000 21420.000       NaN
                             6.0                5.000 30729.600  4008.782
                             43.0               1.000 13719.000       NaN
                             51.0               4.000 21260.000   193.735
                             -                139.000 19178.324  4060.729
               Station wagon 3.4                1.000 13999.000       NaN
                             3.7                2.000 15586.000  1182.283
                             3.9                4.000 15935.000   241.316
                             4.1                1.000 19640.000       NaN
                             4.2                2.000 15660.000  1725.341
                             4.4                3.000 15106.667  1890.882
                             4.5                1.000 20940.000       NaN
                             4.7                1.000 20650.000       NaN
                             4.9                3.000 22593.333  5809.994
                             5.1                1.000 13979.000       NaN
                             5.8                1.000 28999.000       NaN
                             -                  1.000 16500.000       NaN
               Van           -                  1.000 29000.000       NaN
Audi A2        Off-Road      4.9                1.000 28200.000       NaN
Audi A3        Compact       3.0                7.000 17783.571  2300.480
                             3.4                3.000 14613.333  1559.498
                             3.8               27.000 17407.630  2485.921
                             3.9               10.000 16234.300  1308.195
                             4.0               31.000 20621.516  3125.470
                             4.1               11.000 20349.091  1071.078
                             4.2                3.000 15950.000     0.000
                             4.4                3.000 20333.333  3195.439
                             4.5               14.000 31228.714  9890.852
                             4.6                3.000 21916.667  2589.292
                             4.7                1.000 17990.000       NaN
                             4.8                1.000 29950.000       NaN
                             4.9                1.000 16900.000       NaN
                             5.0                9.000 18238.556  6778.785
                             5.1               36.000 13981.111  2048.230
                             5.3                1.000 14900.000       NaN
                             8.3                1.000 67600.000       NaN
                             -                 20.000 18603.200  2959.474
               Convertible   3.8                1.000 20900.000       NaN
                             4.5                1.000 29500.000       NaN
                             4.7                2.000 25450.000  7707.464
                             4.9                1.000 32950.000       NaN
                             5.1                2.000 16446.500  7853.835
                             7.1                1.000 56100.000       NaN
               Coupe         3.8                1.000 18000.000       NaN
                             3.9                2.000 16990.000     0.000
                             4.6                1.000 19000.000       NaN
               Sedans        1.6                3.000 37449.667  1361.635
                             3.0                1.000 17900.000       NaN
                             3.2                2.000 13099.500   212.839
                             3.3               10.000 21033.000  3094.152
                             3.4               16.000 17702.938  2993.833
                             3.5                6.000 23753.167  7502.049
                             3.6                3.000 18530.000  2531.541
                             3.7               14.000 18225.571  1935.619
                             3.8              296.000 17537.334  2829.962
                             3.9              383.000 22975.627  3128.601
                             4.0              421.000 20077.682  2692.619
                             4.1              169.000 19720.645  2699.577
                             4.2               58.000 19917.707  2756.986
                             4.3               19.000 20390.211  3234.483
                             4.4              132.000 22773.235  4026.662
                             4.5              127.000 21540.315  4065.088
                             4.6               48.000 21968.167  2748.347
                             4.7               84.000 20671.226  2439.085
                             4.8               62.000 21816.952  3949.480
                             4.9               33.000 21050.061  7123.232
                             5.0               48.000 21710.833  2757.561
                             5.1              227.000 23941.256  2302.440
                             5.2               48.000 25340.771  1930.664
                             5.3               19.000 22400.579  3901.911
                             5.4                1.000 34738.000       NaN
                             5.5               53.000 23854.019  1761.138
                             5.8                7.000 21070.000  2786.599
                             6.0                1.000 20500.000       NaN
                             6.4                1.000 25600.000       NaN
                             6.5                1.000 58990.000       NaN
                             6.6                1.000 25000.000       NaN
                             8.1                2.000 41750.000  1060.660
                             8.3               17.000 54040.529  9731.997
                             10.0               1.000 17490.000       NaN
                             38.0               2.000 23500.000     0.000
                             40.0               2.000 19500.000     0.000
                             -                303.000 18594.370  3809.233
               Station wagon 3.3                1.000 15990.000       NaN
                             3.8               26.000 15356.115  2587.238
                             3.9               16.000 21160.875  5027.418
                             4.0               24.000 19211.625  3890.649
                             4.1               11.000 20109.000  3042.461
                             4.2               17.000 17882.882  1524.306
                             4.4               28.000 21587.321  3534.564
                             4.5               23.000 22175.565  2766.165
                             4.6                4.000 18914.750  2686.356
                             4.7                9.000 21002.000  3219.499
                             4.8               29.000 20356.621  3853.278
                             4.9                4.000 17435.000  1132.210
                             5.0               34.000 22875.559  1876.601
                             5.1               14.000 22942.000  2910.253
                             5.2                9.000 25001.111  1937.301
                             5.3                9.000 23681.111  3042.521
                             5.5                2.000 25990.000     0.000
                             8.3                1.000 63900.000       NaN
                             -                 21.000 19079.000  3358.451
Opel Astra     Compact       3.0               17.000 12406.412  2293.249
                             3.3                3.000 11450.000   866.025
                             3.4                2.000 10720.000   325.269
                             3.6                1.000 11980.000       NaN
                             3.7               36.000 13040.806  1277.266
                             3.9                3.000  8450.000     0.000
                             4.0                6.000 15779.333  2986.362
                             4.1                3.000 16533.333  1053.961
                             4.3                7.000 18534.714  2606.032
                             4.4                1.000 18950.000       NaN
                             4.5               10.000 15265.300  2097.881
                             5.0                8.000 14923.000  1457.306
                             5.1               16.000 12980.312  1669.057
                             5.4                4.000 19818.250  8501.007
                             5.5                2.000 29847.500   454.670
                             5.6                3.000 26899.000     0.000
                             5.7                1.000 32302.000       NaN
                             5.9                2.000 33496.500  6361.840
                             6.1                1.000 25290.000       NaN
                             6.4                3.000 35761.000  4388.999
                             6.6                1.000 36950.000       NaN
                             -                 55.000 17496.073  5427.034
               Coupe         5.8                1.000 29990.000       NaN
                             6.6                1.000 14490.000       NaN
               Off-Road      5.6                1.000 18590.000       NaN
               Sedans        0.0                1.000 17850.000       NaN
                             3.0                4.000  9760.000   888.107
                             3.3                8.000 12147.500  2570.190
                             3.4               42.000 11908.810  1455.195
                             3.5               30.000 12559.333  1889.373
                             3.6               18.000 12738.056  2917.478
                             3.7               50.000 11014.680  1741.829
                             3.8                2.000 11245.000  1336.432
                             3.9                6.000 11208.333  2653.755
                             4.0                3.000 13616.667  2309.942
                             4.1               11.000 19053.091  3700.240
                             4.2                5.000 11816.000  1339.153
                             4.3               45.000 13825.044  2149.951
                             4.4               66.000 14718.015  2244.176
                             4.5               71.000 14854.592  2170.348
                             4.6                5.000 14474.000  1721.694
                             4.7               67.000 16966.537  1773.052
                             4.8               12.000 18858.167  2994.356
                             4.9               27.000 17623.111  4411.401
                             5.0               16.000 16116.188  1497.582
                             5.1               22.000 14772.955  2702.203
                             5.2                1.000 15400.000       NaN
                             5.4              175.000 15474.777  2999.038
                             5.5               68.000 17812.853  3375.506
                             5.6               30.000 19293.833  6071.295
                             5.7               19.000 21976.211  4274.419
                             5.8               13.000 19269.615  3410.991
                             5.9               26.000 23428.308  2968.446
                             6.0                9.000 17659.444  1536.757
                             6.1               22.000 25096.727  2485.149
                             6.2                5.000 14026.000   916.695
                             6.3                4.000 16222.000  2585.805
                             6.4               10.000 24557.900  7406.387
                             6.5                1.000 14850.000       NaN
                             6.6                7.000 28356.429  3468.741
                             6.7                1.000 10750.000       NaN
                             6.8                4.000 20990.000  4690.416
                             7.1                1.000 12340.000       NaN
                             7.3                2.000 15980.000  1428.356
                             7.4                1.000 31890.000       NaN
                             7.5                1.000 28900.000       NaN
                             -                142.000 15218.725  3625.596
               Station wagon 3.0                3.000 15625.333  1494.182
                             3.3                3.000 10983.333  1227.124
                             3.4                8.000 11640.000  1568.721
                             3.5              112.000 11905.848  1861.255
                             3.6              101.000 11440.000  2152.848
                             3.7               66.000 10478.318  2034.729
                             3.8               31.000 12389.935  3179.237
                             3.9               49.000 12826.490  2705.218
                             4.0                8.000 17237.500  3816.878
                             4.1                1.000 10480.000       NaN
                             4.2                3.000 14846.667  1699.127
                             4.3               30.000 14848.800  2755.733
                             4.4                2.000 13313.000  5208.549
                             4.5              153.000 15542.706  2685.841
                             4.6               95.000 15619.884  2661.995
                             4.7               16.000 15878.750  2888.505
                             4.8               14.000 23266.786  4190.720
                             4.9               15.000 17789.067  3341.314
                             5.0               21.000 18425.762  2609.479
                             5.1               48.000 17234.417  4380.617
                             5.4               60.000 19061.517  2911.031
                             5.5               35.000 16731.714  3847.417
                             5.6               90.000 18633.178  3310.352
                             5.7               21.000 23084.095  5348.663
                             5.8               21.000 25167.857  3555.410
                             5.9                9.000 18792.111  3462.202
                             6.0               17.000 24176.059  5297.994
                             6.1               10.000 21424.500  6886.015
                             6.2                2.000  9990.000   692.965
                             6.3               10.000 14953.800  8534.036
                             6.4                5.000 13270.800  1498.267
                             6.5                9.000 29759.556  4710.535
                             6.6               10.000 23277.900 10931.595
                             6.7               19.000 26357.842  6559.137
                             6.8                1.000 14900.000       NaN
                             -                187.000 14487.829  4721.416
Opel Corsa     Compact       3.0                5.000  7166.000  1703.300
                             3.1                1.000 10900.000       NaN
                             3.2                2.000  9719.000   380.423
                             3.3                3.000  8216.667   596.518
                             3.4                2.000  9724.500  1802.415
                             3.8               28.000  7805.464   540.757
                             3.9                6.000  6981.500  1027.195
                             4.0                1.000 10949.000       NaN
                             4.3                1.000  8900.000       NaN
                             4.6                3.000  8730.667  9317.246
                             4.7               56.000 12741.518  1539.538
                             4.8               48.000 13312.979  2023.437
                             4.9                5.000 11742.200  1316.432

In [ ]:
df.Consumption_comb.replace("-", np.nan, inplace=True)

In [ ]:
df.Consumption_comb.fillna(df.groupby(["make_model","body_type"]).Consumption_comb.transform("mean"),inplace=True)

In [ ]:
df.Consumption_comb.isnull().sum()

9

In [ ]:
df.Consumption_comb.dropna(axis=0, how="all", inplace=True)

In [ ]:
df.Consumption_comb.isnull().sum()

9

### CO2_Emission

In [ ]:
describe("CO2_Emission")

Column Name    :  CO2_Emission
----------------------------------------
Per_of_nulls   :  % 15.3
Num_of_nulls   :  2436
Num_of_uniques :  120
----------------------------------------
NaN        2436
120.000     740
99.000      545
97.000      537
104.000     501
10.000      477
103.000     445
114.000     382
124.000     372
107.000     362
108.000     362
119.000     361
106.000     349
128.000     329
126.000     282
85.000      275
118.000     270
110.000     266
127.000     257
117.000     254
111.000     237
113.000     235
109.000     234
139.000     224
140.000     218
129.000     213
135.000     202
105.000     202
9.000       198
130.000     180
123.000     178
150.000     174
11.000      171
143.000     171
95.000      161
116.000     157
141.000     156
98.000      151
136.000     145
133.000     145
137.000     133
125.000     132
134.000     130
145.000     126
149.000     117
153.000     113
147.000     109
101.000     105
13.000      100
115.000      86
1.000        84
121.000      82
138.000      75
93.000       66
14.000       59
168.000      58
131.000      48
148.000      48
144.000      40
154.000      40
94.000       37
100.000      36
146.000      36
90.000       35
151.000      34
91.000       31
186.000      30
15.000       28
187.000      26
8.000        25
17.000       25
96.000       22
189.000      19
89.000       19
157.000      18
158.000      17
169.000      15
88.000       15
156.000      14
164.000      13
170.000      10
161.000      10
155.000       8
175.000       8
166.000       8
188.000       7
159.000       7
174.000       6
87.000        6
197.000       4
36.000        3
194.000       3
5.000         3
12.087        3
84.000        2
191.000       2
16.000        2
167.000       2
0.000         2
199.000       2
13.983        1
183.000       1
171.000       1
45.000        1
180.000       1
177.000       1
331.000       1
181.000       1
160.000       1
14.457        1
165.000       1
184.000       1
80.000        1
239.000       1
190.000       1
253.000       1
990.000       1
12.324        1
1.060         1
51.000        1
193.000       1
Name: CO2_Emission, dtype: int64

In [ ]:
df.CO2_Emission.fillna("-",inplace=True)

In [ ]:
df.CO2_Emission.replace("-", np.nan, inplace=True)

In [ ]:
for group1 in list(df["make_model"].unique()):
            for group2 in list(df["body_type"].unique()):
                cond1 = df["make_model"]==group1
                cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
                df.loc[cond2, "CO2_Emission"] = df.loc[cond2, "CO2_Emission"].fillna(df[cond2]["CO2_Emission"].median()).fillna(df[cond1]["CO2_Emission"].median())

In [ ]:
df.CO2_Emission.isnull().sum()

1

In [ ]:
df.CO2_Emission.dropna(axis=0, how="all", inplace=True)

In [ ]:
df.CO2_Emission.isnull().sum()

1

### Emission_Class

In [ ]:
describe("Emission_Class")

Column Name    :  Emission_Class
----------------------------------------
Per_of_nulls   :  % 22.79
Num_of_nulls   :  3628
Num_of_uniques :  3
----------------------------------------
Euro 6    12173
NaN        3628
Euro 5       78
Euro 4       40
Name: Emission_Class, dtype: int64

In [ ]:
df.Emission_Class.fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model","body_type","Emission_Class"]).price.describe()

                                               count      mean       std  \
make_model     body_type     Emission_Class
Audi A1        Compact       -               182.000 19434.445  4684.162
                             Euro 4            1.000 12990.000       NaN
                             Euro 5            5.000 16277.400  3257.660
                             Euro 6          851.000 19161.355  4530.829
               Coupe         -                 1.000 15900.000       NaN
                             Euro 6            1.000 13950.000       NaN
               Sedans        -               374.000 20684.487  4437.752
                             Euro 5            4.000 14210.000  1478.310
                             Euro 6         1173.000 18029.677  4267.007
               Station wagon -                 2.000 21499.000 10606.602
                             Euro 6           19.000 17423.211  3634.239
               Van           -                 1.000 29000.000       NaN
Audi A2        Off-Road      Euro 6            1.000 28200.000       NaN
Audi A3        Compact       -                51.000 21620.294  8504.860
                             Euro 6          131.000 18013.885  5748.379
               Convertible   -                 1.000 32950.000       NaN
                             Euro 6            7.000 27184.714 14368.232
               Coupe         Euro 6            4.000 17745.000   962.653
               Sedans        -               393.000 21549.725  4144.374
                             Euro 5            6.000 17331.667  2444.589
                             Euro 6         2222.000 21090.937  4937.563
               Station wagon -                36.000 20257.667  3579.809
                             Euro 5            1.000 14550.000       NaN
                             Euro 6          245.000 20772.090  4817.316
Opel Astra     Compact       -                84.000 17961.869  7294.560
                             Euro 6          101.000 14734.248  4315.934
               Coupe         -                 1.000 14490.000       NaN
                             Euro 6            1.000 29990.000       NaN
               Off-Road      Euro 6            1.000 18590.000       NaN
               Sedans        -               267.000 16976.948  4299.726
                             Euro 5            8.000 12767.500  2073.753
                             Euro 6          778.000 15648.126  4389.844
               Station wagon -               290.000 16143.379  5364.719
                             Euro 5            6.000 11058.000  1649.262
                             Euro 6          989.000 15552.255  5128.534
Opel Corsa     Compact       -               302.000 11256.553  3381.208
                             Euro 5            1.000  7790.000       NaN
                             Euro 6         1016.000 11779.810  2956.036
               Coupe         -                 2.000  9300.000  2545.584
                             Euro 6           11.000  8676.364  1509.320
               Off-Road      Euro 5            3.000  8166.667   461.880
               Sedans        -               173.000 10817.347  3133.704
                             Euro 4            1.000 14477.000       NaN
                             Euro 5            4.000  8430.000  2267.436
                             Euro 6          697.000 10058.050  2470.701
               Transporter   -                 1.000  7450.000       NaN
                             Euro 6            6.000  7683.333  2486.899
               Van           -                 2.000  7900.000     0.000
Opel Insignia  Compact       -                 9.000 29907.889 12878.987
                             Euro 6           18.000 27931.167 10743.900
               Coupe         -                 1.000 17094.000       NaN
               Off-Road      -                 5.000 32981.800  1234.860
                             Euro 6            2.000 20625.000 11136.932
               Sedans        -               297.000 22263.771  7609.370
                             Euro 4            1.000 13850.000       NaN
                             Euro 5            3.000 12363.333  3343.207
                             Euro 6          599.000 20824.446  7254.712
               Station wagon -               358.000 21556.522  7882.060
                             Euro 4            1.000 12000.000       NaN
                             Euro 5           10.000 15330.500  2485.172
                             Euro 6         1293.000 21443.326  7711.415
               Van           -                 1.000 20980.000       NaN
Renault Clio   Compact       -               160.000 12562.894  4036.983
                             Euro 5            2.000 12325.000  6470.027
                             Euro 6          322.000 12694.752  4124.536
               Coupe         Euro 6            1.000 17990.000       NaN
               Off-Road      Euro 6            2.000 12845.000  7276.129
               Sedans        -               242.000 10637.934  2851.188
                             Euro 4            2.000  9700.000   424.264
                             Euro 5           14.000  9317.643  2277.227
                             Euro 6          726.000 12469.219  4924.664
               Station wagon -                65.000 12624.969  3723.445
                             Euro 4            1.000 10790.000       NaN
                             Euro 5            8.000  9152.250  2083.300
                             Euro 6          263.000 10817.951  2740.630
               Transporter   -                19.000  8571.368  1376.542
                             Euro 5            1.000  7000.000       NaN
                             Euro 6            9.000  8484.333  1289.331
               Van           -                 2.000  9650.000   353.553
Renault Duster Off-Road      -                 2.000 11425.000   813.173
                             Euro 4           32.000 13343.000  1599.159
Renault Espace Compact       -                 3.000 33496.667  9505.000
                             Euro 6            3.000 26596.667 11770.133
               Coupe         -                 2.000 30567.000  5052.985
               Off-Road      -                 3.000 23533.333  7476.686
                             Euro 6            5.000 27100.000  4103.657
               Sedans        -                 7.000 26078.429  4315.543
                             Euro 6           14.000 32039.429  8161.543
               Station wagon -                 8.000 26527.500  7548.065
                             Euro 5            1.000 30980.000       NaN
                             Euro 6           82.000 27346.756  8929.043
               Transporter   -                 6.000 20800.000  1985.951
                             Euro 6           46.000 22842.109  4395.244
               Van           -               275.000 31589.771  8614.712
                             Euro 4            1.000 35750.000       NaN
                             Euro 5            1.000 24900.000       NaN
                             Euro 6          534.000 30565.294  8760.778

                                                  min       25%       50%  \
make_model     body_type     Emission_Class
Audi A1        Compact       -               9950.000 15806.750 19355.500
                             Euro 4         12990.000 12990.000 12990.000
                             Euro 5         10999.000 16800.000 16800.000
                             Euro 6         10490.000 15765.000 18333.000
               Coupe         -              15900.000 15900.000 15900.000
                             Euro 6         13950.000 13950.000 13950.000
               Sedans        -              11990.000 16817.500 21245.000
                             Euro 5         12950.000 12980.000 13995.000
                             Euro 6          8999.000 15090.000 16856.000
               Station wagon -              13999.000 17749.000 21499.000
                             Euro 6         12950.000 15800.000 16422.000
               Van           -              29000.000 29000.000 29000.000
Audi A2        Off-Road      Euro 6         28200.000 28200.000 28200.000
Audi A3        Compact       -              12900.000 15945.000 17900.000
                             Euro 6         13444.000 13500.000 17550.000
               Convertible   -              32950.000 32950.000 32950.000
                             Euro 6         10893.000 20450.000 22000.000
               Coupe         Euro 6         16990.000 16990.000 17495.000
               Sedans        -              10950.000 17950.000 22690.000
                             Euro 5         13900.000 15725.000 17945.000
                             Euro 6         10550.000 17996.750 20980.000
               Station wagon -              12990.000 17825.000 19732.500
                             Euro 5         14550.000 14550.000 14550.000
                             Euro 6          5555.000 17900.000 21200.000
Opel Astra     Compact       -               9000.000 13993.750 15974.000
                             Euro 6          8450.000 12490.000 13899.000
               Coupe         -              14490.000 14490.000 14490.000
                             Euro 6         29990.000 29990.000 29990.000
               Off-Road      Euro 6         18590.000 18590.000 18590.000
               Sedans        -               6950.000 14534.500 16977.000
                             Euro 5         11700.000 11700.000 11700.000
                             Euro 6          6500.000 12500.000 15000.000
               Station wagon -               6480.000 11600.000 16494.500
                             Euro 5          9290.000  9970.000 10539.000
                             Euro 6           255.000 11900.000 14990.000
Opel Corsa     Compact       -                331.000  8325.000 10465.000
                             Euro 5          7790.000  7790.000  7790.000
                             Euro 6           120.000  9400.000 10999.500
               Coupe         -               7500.000  8400.000  9300.000
                             Euro 6          6900.000  7500.000  8500.000
               Off-Road      Euro 5          7900.000  7900.000  7900.000
               Sedans        -               5890.000  7950.000 10500.000
                             Euro 4         14477.000 14477.000 14477.000
                             Euro 5          5970.000  7117.500  8225.000
                             Euro 6            13.000  8300.000  9550.000
               Transporter   -               7450.000  7450.000  7450.000
                             Euro 6          5250.000  5487.500  7600.000
               Van           -               7900.000  7900.000  7900.000
Opel Insignia  Compact       -              13490.000 20900.000 34995.000
                             Euro 6         10350.000 19150.000 29992.500
               Coupe         -              17094.000 17094.000 17094.000
               Off-Road      -              31505.000 32345.000 32793.000
                             Euro 6         12750.000 16687.500 20625.000
               Sedans        -               9900.000 16690.000 20900.000
                             Euro 4         13850.000 13850.000 13850.000
                             Euro 5          8600.000 11050.000 13500.000
                             Euro 6          9650.000 16400.000 19500.000
               Station wagon -               8980.000 14991.250 21432.500
                             Euro 4         12000.000 12000.000 12000.000
                             Euro 5         12400.000 12925.000 15370.000
                             Euro 6          8290.000 15490.000 19999.000
               Van           -              20980.000 20980.000 20980.000
Renault Clio   Compact       -               5800.000 10365.000 11299.000
                             Euro 5          7750.000 10037.500 12325.000
                             Euro 6          5890.000  9999.000 11400.000
               Coupe         Euro 6         17990.000 17990.000 17990.000
               Off-Road      Euro 6          7700.000 10272.500 12845.000
               Sedans        -               6000.000  8492.500  9990.000
                             Euro 4          9400.000  9550.000  9700.000
                             Euro 5          7500.000  7999.250  8500.000
                             Euro 6          5445.000  9325.000 10545.000
               Station wagon -               7250.000  9450.000 11400.000
                             Euro 4         10790.000 10790.000 10790.000
                             Euro 5          7200.000  7800.000  8249.000
                             Euro 6          5900.000  8900.000 10450.000
               Transporter   -               5900.000  7890.000  8590.000
                             Euro 5          7000.000  7000.000  7000.000
                             Euro 6          6490.000  7800.000  7900.000
               Van           -               9400.000  9525.000  9650.000
Renault Duster Off-Road      -              10850.000 11137.500 11425.000
                             Euro 4         10900.000 12162.500 13219.500
Renault Espace Compact       -              23990.000 28745.000 33500.000
                             Euro 6         17900.000 19900.000 21900.000
               Coupe         -              26994.000 28780.500 30567.000
               Off-Road      -              14900.000 21375.000 27850.000
                             Euro 6         22500.000 24900.000 25700.000
               Sedans        -              18999.000 23800.000 25900.000
                             Euro 6         23990.000 25995.000 29240.000
               Station wagon -              19250.000 21480.000 24490.000
                             Euro 5         30980.000 30980.000 30980.000
                             Euro 6         16900.000 20455.000 23950.000
               Transporter   -              17950.000 19575.000 20950.000
                             Euro 6         14999.000 19912.500 21000.000
               Van           -              16480.000 24990.000 30160.000
                             Euro 4         35750.000 35750.000 35750.000
                             Euro 5         24900.000 24900.000 24900.000
                             Euro 6         12614.000 24700.000 29655.500

                                                  75%       max
make_model     body_type     Emission_Class
Audi A1        Compact       -              22480.000 31990.000
                             Euro 4         12990.000 12990.000
                             Euro 5         16800.000 19988.000
                             Euro 6         22145.000 29197.000
               Coupe         -              15900.000 15900.000
                             Euro 6         13950.000 13950.000
               Sedans        -              23800.000 29000.000
                             Euro 5         15225.000 15900.000
                             Euro 6         20500.000 37900.000
               Station wagon -              25249.000 28999.000
                             Euro 6         18540.000 28890.000
               Van           -              29000.000 29000.000
Audi A2        Off-Road      Euro 6         28200.000 28200.000
Audi A3        Compact       -              23921.000 41495.000
                             Euro 6         20300.000 67600.000
               Convertible   -              32950.000 32950.000
                             Euro 6         30200.000 56100.000
               Coupe         Euro 6         18250.000 19000.000
               Sedans        -              24989.000 28490.000
                             Euro 5         18522.500 20500.000
                             Euro 6         23286.750 74600.000
               Station wagon -              23400.250 26990.000
                             Euro 5         14550.000 14550.000
                             Euro 6         23639.000 63900.000
Opel Astra     Compact       -              17925.000 39433.000
                             Euro 6         15950.000 36950.000
               Coupe         -              14490.000 14490.000
                             Euro 6         29990.000 29990.000
               Off-Road      Euro 6         18590.000 18590.000
               Sedans        -              18425.000 30750.000
                             Euro 5         12680.000 17600.000
                             Euro 6         17889.750 32950.000
               Station wagon -              18890.000 33470.000
                             Euro 5         12309.500 13300.000
                             Euro 6         17980.000 34900.000
Opel Corsa     Compact       -              13999.000 18622.000
                             Euro 5          7790.000  7790.000
                             Euro 6         14213.000 18501.000
               Coupe         -              10200.000 11100.000
                             Euro 6          9650.000 10990.000
               Off-Road      Euro 5          8300.000  8700.000
               Sedans        -              13400.000 18490.000
                             Euro 4         14477.000 14477.000
                             Euro 5          9537.500 11300.000
                             Euro 6         11294.000 18490.000
               Transporter   -               7450.000  7450.000
                             Euro 6          9675.000 10500.000
               Van           -               7900.000  7900.000
Opel Insignia  Compact       -              38679.000 49884.000
                             Euro 6         37546.750 39990.000
               Coupe         -              17094.000 17094.000
               Off-Road      -              33490.000 34776.000
                             Euro 6         24562.500 28500.000
               Sedans        -              25588.000 49350.000
                             Euro 4         13850.000 13850.000
                             Euro 5         14245.000 14990.000
                             Euro 6         23595.000 40990.000
               Station wagon -              24490.000 42995.000
                             Euro 4         12000.000 12000.000
                             Euro 5         16988.750 19490.000
                             Euro 6         24290.000 52120.000
               Van           -              20980.000 20980.000
Renault Clio   Compact       -              15485.000 29740.000
                             Euro 5         14612.500 16900.000
                             Euro 6         14990.000 28949.000
               Coupe         Euro 6         17990.000 17990.000
               Off-Road      Euro 6         15417.500 17990.000
               Sedans        -              11287.500 22800.000
                             Euro 4          9850.000 10000.000
                             Euro 5          9275.000 14500.000
                             Euro 6         14990.000 31500.000
               Station wagon -              15990.000 19490.000
                             Euro 4         10790.000 10790.000
                             Euro 5         10202.500 13250.000
                             Euro 6         11500.000 20800.000
               Transporter   -               9340.000 10798.000
                             Euro 5          7000.000  7000.000
                             Euro 6          9262.000 10460.000
               Van           -               9775.000  9900.000
Renault Duster Off-Road      -              11712.500 12000.000
                             Euro 4         14505.000 16033.000
Renault Espace Compact       -              38250.000 43000.000
                             Euro 6         30945.000 39990.000
               Coupe         -              32353.500 34140.000

In [ ]:
df.Emission_Class.replace("-", np.nan, inplace=True)

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Emission_Class"].mode())
            if mode != []:
                df.loc[cond, "Emission_Class"] = df.loc[cond, "Emission_Class"].fillna(df[cond]["Emission_Class"].mode()[0])
            else:
                df.loc[cond, "Emission_Class"] = df.loc[cond, "Emission_Class"].fillna(df["Emission_Class"].mode()[0])

In [ ]:
df.Emission_Class.value_counts(dropna=False)

Euro 6    15799
Euro 5       78
Euro 4       42
Name: Emission_Class, dtype: int64

### Comfort_Convenience

In [ ]:
describe("Comfort_Convenience")

Column Name    :  Comfort_Convenience
----------------------------------------
Per_of_nulls   :  % 5.78
Num_of_nulls   :  920
Num_of_uniques :  6198
----------------------------------------
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                   216
Air conditioning,Electrical side mirrors,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                               134
Air conditioning,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                       130
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system                                                                                                                                                   105
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...
Air conditioning,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors rear,Power windows,Rain sensor,Split rear seats,Start-stop system,Tinted windows                                                                                                                                                                                                           1
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Heated steering wheel,Hill Holder,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Sunroof                                                                                                1
Air conditioning,Armrest,Cruise control,Electrical side mirrors,Heated steering wheel,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Split rear seats,Start-stop system,Tinted windows                                                                                                                 1
Air conditioning,Automatic climate control,Cruise control,Electrical side mirrors,Leather steering wheel,Light sensor,Multi-function steering wheel,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating                                                                                                                                                                                                                1
Air conditioning,Automatic climate control,Cruise control,Electrically heated windshield,Electrical side mirrors,Electric tailgate,Heads-up display,Heated steering wheel,Hill Holder,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Navigation system,Park Distance Control,Parking assist system camera,Parking assist system self-steering,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Sunroof      1
Name: Comfort_Convenience, Length: 6199, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Comfort_Convenience"].mode())
            if mode != []:
                df.loc[cond, "Comfort_Convenience"] = df.loc[cond, "Comfort_Convenience"].fillna(df[cond]["Comfort_Convenience"].mode()[0])
            else:
                df.loc[cond, "Comfort_Convenience"] = df.loc[cond, "Comfort_Convenience"].fillna(df["Comfort_Convenience"].mode()[0])

In [ ]:
df.Comfort_Convenience.isnull().sum()

0

### Entertainment_Media

In [ ]:
describe("Entertainment_Media")

Column Name    :  Entertainment_Media
----------------------------------------
Per_of_nulls   :  % 8.63
Num_of_nulls   :  1374
Num_of_uniques :  346
----------------------------------------
NaN                                                                                                               1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                                        1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                                     982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                                           783
On-board computer,Radio                                                                                            487
Radio                                                                                                              477
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,USB                                               465
On-board computer                                                                                                  461
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio                                               404
Bluetooth,On-board computer,Radio                                                                                  397
Bluetooth,Hands-free equipment,On-board computer,Radio                                                             378
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                              327
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio                                                         295
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,USB                                           285
Bluetooth,Radio                                                                                                    271
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,USB                                       252
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio                                                   240
Bluetooth,On-board computer                                                                                        232
Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system,USB                                            188
Bluetooth,On-board computer,Radio,USB                                                                              180
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                175
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,USB                             157
Bluetooth,MP3,On-board computer,Radio,USB                                                                          154
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system,USB                              134
Bluetooth,Hands-free equipment,On-board computer                                                                   130
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                          130
Bluetooth                                                                                                          125
Bluetooth,Hands-free equipment,MP3,On-board computer,USB                                                           124
Bluetooth,Hands-free equipment                                                                                     121
Bluetooth,CD player,MP3,On-board computer,Radio                                                                    120
Bluetooth,Hands-free equipment,On-board computer,USB                                                               115
Bluetooth,Hands-free equipment,MP3,Radio,USB                                                                       115
CD player,On-board computer,Radio                                                                                  113
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB                                        110
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system,USB                                  108
Bluetooth,CD player,On-board computer,Radio,USB                                                                    104
Bluetooth,CD player,MP3,On-board computer,Radio,USB                                                                102
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system                                   93
Bluetooth,Hands-free equipment,Radio,USB                                                                            93
Bluetooth,Digital radio,On-board computer,Radio,USB                                                                 87
Bluetooth,USB                                                                                                       83
Bluetooth,Hands-free equipment,Radio                                                                                83
Hands-free equipment,On-board computer,Radio,USB                                                                    81
Bluetooth,Hands-free equipment,MP3,On-board computer                                                                79
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                            78
Bluetooth,Radio,USB                                                                                                 74
CD player,MP3,On-board computer,Radio                                                                               73
Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system,USB                     70
Bluetooth,CD player,Radio,USB                                                                                       65
Bluetooth,CD player,On-board computer,Radio                                                                         63
On-board computer,Radio,USB                                                                                         59
CD player,MP3,Radio                                                                                                 57
Bluetooth,CD player,Hands-free equipment,MP3,Radio,USB                                                              56
Bluetooth,CD player,On-board computer                                                                               56
Bluetooth,MP3,On-board computer,Radio                                                                               56
Bluetooth,CD player,MP3,On-board computer                                                                           54
Bluetooth,MP3,On-board computer                                                                                     50
Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system                                       50
USB                                                                                                                 46
Bluetooth,CD player,Hands-free equipment,MP3,Radio                                                                  43
Bluetooth,On-board computer,Radio,Sound system                                                                      43
Hands-free equipment,On-board computer,Radio                                                                        43
Hands-free equipment,On-board computer                                                                              42
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,Sound system                                             42
CD player,Radio                                                                                                     41
CD player,Hands-free equipment,Radio,Sound system                                                                   40
Bluetooth,Digital radio,MP3,On-board computer,Radio,USB                                                             39
Digital radio,Hands-free equipment,On-board computer,Radio                                                          38
MP3,On-board computer,Radio                                                                                         38
Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio,USB                                  36
Digital radio,On-board computer,Radio                                                                               36
MP3,Radio                                                                                                           36
Bluetooth,Digital radio,Hands-free equipment,On-board computer,USB                                                  36
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,USB                                              33
Bluetooth,CD player,Radio                                                                                           32
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio                                                32
Bluetooth,Hands-free equipment,MP3,Radio                                                                            30
Radio,USB                                                                                                           29
Bluetooth,On-board computer,USB                                                                                     28
CD player                                                                                                           28
CD player,On-board computer                                                                                         28
Bluetooth,CD player,MP3,On-board computer,Radio,Sound system,USB                                                    27
CD player,MP3,On-board computer,Radio,USB                                                                           27
Bluetooth,CD player,Digital radio,MP3,On-board computer,Radio,USB                                                   27
Bluetooth,CD player,Hands-free equipment,On-board computer,USB                                                      26
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                  25
Bluetooth,CD player,Hands-free equipment,Radio                                                                      25
On-board computer,Radio,Sound system                                                                                25
MP3,On-board computer,Radio,USB                                                                                     24
CD player,Hands-free equipment,On-board computer,Radio,USB                                                          24
CD player,Hands-free equipment,On-board computer                                                                    23
Bluetooth,Hands-free equipment,MP3,On-board computer,Sound system,USB                                               23
On-board computer,USB                                                                                               23
Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system                                                 23
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Sound system,USB                                 23
On-board computer,Sound system                                                                                      21
Radio,Sound system                                                                                                  21
Bluetooth,Digital radio,Hands-free equipment,Radio,USB                                                              20
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system                     20
Digital radio,Radio                                                                                                 20
Bluetooth,Hands-free equipment,MP3,USB                                                                              19
CD player,Hands-free equipment,On-board computer,Radio                                                              19
Bluetooth,Hands-free equipment,USB                                                                                  18
Bluetooth,CD player,Hands-free equipment,On-board computer                                                          18
Bluetooth,CD player,MP3,Radio,USB                                                                                   18
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,USB                                                  17
Bluetooth,CD player,Hands-free equipment,Radio,USB                                                                  17
CD player,On-board computer,Radio,USB                                                                               17
Bluetooth,Digital radio,Radio,USB                                                                                   16
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Sound system,USB                                     16
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Radio,Sound system                                   16
Bluetooth,Hands-free equipment,MP3,Radio,Sound system,USB                                                           16
Bluetooth,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system                               16
Bluetooth,CD player,MP3,On-board computer,Radio,Sound system                                                        16
Bluetooth,MP3,On-board computer,USB                                                                                 15
CD player,Hands-free equipment,Radio                                                                                15
Bluetooth,Digital radio,On-board computer                                                                           15
Sound system                                                                                                        15
Bluetooth,Hands-free equipment,On-board computer,Sound system,USB                                                   15
Bluetooth,CD player                                                                                                 14
Bluetooth,CD player,Hands-free equipment,MP3,Radio,Sound system,USB                                                 14
MP3,On-board computer                                                                                               14
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,USB                                    14
Hands-free equipment,Radio                                                                                          14
Bluetooth,Digital radio,Hands-free equipment,Radio,Sound system,USB                                                 14
Bluetooth,CD player,On-board computer,USB                                                                           14
Bluetooth,Digital radio,Hands-free equipment,MP3,Radio,USB                                                          13
Bluetooth,Hands-free equipment,Radio,Sound system,USB                                                               13
Bluetooth,On-board computer,Radio,Sound system,USB                                                                  13
Bluetooth,MP3,USB                                                                                                   13
Bluetooth,Digital radio,On-board computer,Radio,Sound system,USB                                                    13
Bluetooth,Digital radio,Hands-free equipment,MP3,Radio,Sound system,USB                                             13
Bluetooth,CD player,MP3,Radio,Sound system,USB                                                                      13
Bluetooth,Digital radio,On-board computer,Radio                                                                     13
Hands-free equipment                                                                                                13
CD player,Hands-free equipment                                                                                      13
Bluetooth,CD player,Digital radio,Hands-free equipment,On-board computer,Radio                                      12
CD player,MP3,On-board computer                                                                                     12
Sound system,USB                                                                                                    12
Bluetooth,CD player,Hands-free equipment                                                                            11
Hands-free equipment,On-board computer,USB                                                                          11
Digital radio,MP3,On-board computer,Radio                                                                           10
Bluetooth,Digital radio,On-board computer,USB                                                                       10
Bluetooth,Radio,Sound system,USB                                                                                    10
Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,Television,USB      10
Bluetooth,CD player,MP3,Radio                                                                                       10
Bluetooth,CD player,Hands-free equipment,Radio,Sound system                                                         10
Bluetooth,CD player,Digital radio,MP3,On-board computer,Radio,Sound system,USB                                       9
MP3,On-board computer,USB                                                                                            9
Digital radio                                                                                                        8
Bluetooth,Digital radio,MP3,On-board computer,Radio,Sound system,USB                                                 8
Bluetooth,CD player,Digital radio,On-board computer,Radio,USB                                                        8
Bluetooth,Digital radio,Hands-free equipment,On-board computer,Sound system                                          8
Bluetooth,Hands-free equipment,MP3,On-board computer,Sound system                                                    8
Bluetooth,CD player,MP3,On-board computer,USB                                                                        8
Bluetooth,CD player,On-board computer,Radio,Sound system,USB                                                         8
CD player,Hands-free equipment,MP3,On-board computer,Radio                                                           8
Bluetooth,MP3,On-board computer,Radio,Sound system,USB                                                               7
Bluetooth,Digital radio,Hands-free equipment,On-board computer                                                       7
Bluetooth,CD player,Hands-free equipment,On-board computer,Sound system,USB                                          7
Bluetooth,CD player,Digital radio,Hands-free equipment,Radio,USB                                                     7
CD player,MP3,On-board computer,Radio,Sound system                                                                   7
MP3,On-board computer,Radio,Sound system,USB                                                                         7
Bluetooth,CD player,Digital radio,MP3,On-board computer,Radio                                                        7
Digital radio,Hands-free equipment,MP3,On-board computer,Radio                                                       7
Hands-free equipment,Sound system                                                                                    7

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Entertainment_Media"].mode())
            if mode != []:
                df.loc[cond, "Entertainment_Media"] = df.loc[cond, "Entertainment_Media"].fillna(df[cond]["Entertainment_Media"].mode()[0])
            else:
                df.loc[cond, "Entertainment_Media"] = df.loc[cond, "Entertainment_Media"].fillna(df["Entertainment_Media"].mode()[0])

In [ ]:
df.Entertainment_Media.isnull().sum()

0

### Safety_Security

In [ ]:
describe("Safety_Security")

Column Name    :  Safety_Security
----------------------------------------
Per_of_nulls   :  % 6.17
Num_of_nulls   :  982
Num_of_uniques :  4443
----------------------------------------
NaN                                                                                                                                                                                                                                                                                                                                                               982
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                      538
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                                 480
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Xenon headlights                                                                                                                                275
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                           272
                                                                                                                                                                                                                                                                                                                                                                 ...
ABS,Central door lock,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag                                                                                                                                                                                                                                              1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                 1
ABS,Adaptive Cruise Control,Alarm system,Central door lock,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Lane departure warning system,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Xenon headlights                                                1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Power steering,Tire pressure monitoring system,Traction control                                                                                                                                                  1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Fog lights,Immobilizer,Isofix,Lane departure warning system,LED Daytime Running Lights,LED Headlights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traffic sign recognition      1
Name: Safety_Security, Length: 4444, dtype: int64

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["Safety_Security"].mode())
            if mode != []:
                df.loc[cond, "Safety_Security"] = df.loc[cond, "Safety_Security"].fillna(df[cond]["Safety_Security"].mode()[0])
            else:
                df.loc[cond, "Safety_Security"] = df.loc[cond, "Safety_Security"].fillna(df["Safety_Security"].mode()[0])

In [ ]:
df.Safety_Security.isnull().sum()

0

### The End of the Part2

In [ ]:
df.shape

(15919, 26)

In [ ]:
df.isnull().sum()

make_model             0
body_type              0
price                  0
vat                    0
km                     0
Type                   0
Fuel                   0
Gears                  0
Extras                 0
Previous_Owners        0
hp_kW                  0
age                    0
Paint_Type             0
Upholstery_type        0
Nr_of_Doors            0
Nr_of_Seats            0
Gearing_Type           0
Displacement_cc        0
Weight_kg              0
Drive_chain            0
Consumption_comb       9
CO2_Emission           1
Emission_Class         0
Comfort_Convenience    0
Entertainment_Media    0
Safety_Security        0
dtype: int64

In [ ]:
df.dropna(axis=0, inplace=True)

In [ ]:
df.isnull().sum()

make_model             0
body_type              0
price                  0
vat                    0
km                     0
Type                   0
Fuel                   0
Gears                  0
Extras                 0
Previous_Owners        0
hp_kW                  0
age                    0
Paint_Type             0
Upholstery_type        0
Nr_of_Doors            0
Nr_of_Seats            0
Gearing_Type           0
Displacement_cc        0
Weight_kg              0
Drive_chain            0
Consumption_comb       0
CO2_Emission           0
Emission_Class         0
Comfort_Convenience    0
Entertainment_Media    0
Safety_Security        0
dtype: int64

In [ ]:
df.to_csv("missing_cleaned_data_scout.csv", index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored